### ISSUE TITLE
Giving the user a list of providers:

### ISSUE THREAD

**Issue by notadoctorphd** [mov-cli/mov-cli#10]
This is more of a life improvement more than anything else. Instead of exiting out of the program after incorrect input of  "calls:" , there could be a print("Please select from the following list of options") that keeps the loop running and allows for another entry. So, line 40 in Main.py could have an option to allow the user another try. 

This is not a big deal if they have read the code/docs but could help with ease-of-use.

Great job so far.

**Comment by Poseidon444** [comment]
Will be added in today's commit

**Comment by Poseidon444** [comment]
Done!
![image](https://user-images.githubusercontent.com/87462580/172046453-b20a3dad-bdfe-4164-8edd-205fdfc091ef.png)
