### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by umop3plsdn** [mov-cli/mov-cli#101]
**Describe the bug**
A clear and concise description of what the bug is. Explain the steps that you took leading up to the bug to help aid in recreating it.
Anything I type in for search as soon as it yields the results I get the error
**Expected behavior**
Expect mpv to pop up with selected choice
**Screenshots**
![2023-01-21-12:18:56](https://user-images.githubusercontent.com/696094/213878939-076f4945-9b41-40da-9069-3f8a493470a6.png)

**Error**
* Attach Screenshots or Terminal output
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 0.5.8]
Linux 0.6.9

**Additional context**

**Possible cause**
If you have a hunch on what might be causing this, please add it here.

**Possible solution**
If you know a way we could fix this, please add it here.

**Version**
If you don't use the latest Version and create a Bug-Report, it will be closed and left unanswered.

**Comment by ghost** [comment]
It's a problem with https://github.com/consumet/rapidclown.

**Comment by umop3plsdn** [comment]
good to know it wasn't me =)
