### ISSUE TITLE
[FEATURE] paganiation support in search results

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#106]
**Describe the feature/change you'd like**
currently, the cli retrieves only the content available in the 1st page, and the fzf selection in search result works only in that page.

this issue is to requesting the implementation of the paganiation to the cli, I have also added a project below which I have been using recently and which has paganiation for results.

**Additional context**
reference: https://github.com/mps-youtube/yewtube

**Comment by THEGOLDENPRO** [comment]
alright exists in v4 scrapers :+1:
