### ISSUE TITLE
[BUG] Github Pages not rendering properly

### ISSUE THREAD

**Issue by matdexir** [mov-cli/mov-cli#107]
**Describe the bug**
Hey guys, your github pages is not rendering properly. Not sure if you have not caught this yet.

**Expected behavior**
HTML tags should not be visible and render properly.

**Screenshots**If applicable, add screenshots to help explain your problem.
![2023-01-29_13-19](https://user-images.githubusercontent.com/58453130/215306763-1dfb048b-04e4-4d46-98c3-4f8594bd7736.png)

**Error**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 6.1.8
 - Browser: Firefox 109.0

**Additional context**
N/A

**Possible cause**
I think it's the theme used in the configuration

**Possible solution**
Write Custom CSS or Maybe add extra space in between each paragraph

**Version**
N/A

**Comment by ghost** [comment]
> **Describe the bug** Hey guys, your github pages is not rendering properly. Not sure if you have not caught this yet.
> 
> **Expected behavior** HTML tags should not be visible and render properly.
> 
> **Screenshots**If applicable, add screenshots to help explain your problem. ![2023-01-29_13-19](https://user-images.githubusercontent.com/58453130/215306763-1dfb048b-04e4-4d46-98c3-4f8594bd7736.png)
> 
> **Error** N/A
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Linux
> 
>     * Version: 6.1.8
> 
>     * Browser: Firefox 109.0
> 
> 
> **Additional context** N/A
> 
> **Possible cause** I think it's the theme used in the configuration
> 
> **Possible solution** Write Custom CSS or Maybe add extra space in between each paragraph
> 
> **Version** N/A

Problem with that is i don't want that github always publishes this site.

We do have a repo which is our homepage but i am not a html dev and i coded this https://github.com/mov-cli/mov-cli.github.io so it looks like trash on phone and looks trash in general.

**Comment by matdexir** [comment]
Then in that case, I think it's a github action issue. You could go to settings -> Github Pages/Pages and, in the Build Section, instead of Deploy from Branch, choose Github actions.
It should prevent it from auto-deploying.
![2023-01-29_15-03](https://user-images.githubusercontent.com/58453130/215310721-5ecc6284-57f1-486e-8b49-041b8146e17b.png)

**Comment by ghost** [comment]
i did that still it deployed, but i changed it again to github actions

**Comment by matdexir** [comment]
Too bad then. I will close this issue since I don't think there's any valid reason to keep it open.
