### ISSUE TITLE
[FEATURE] command functions

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#108]
**Describe the feature/change you'd like**
add command functions to invoke the certain functions like search again, switch providers, etc.

example: from a search result
```
  [1] Maanaadu | Must Watch MOVIE
  [2] Maanavan | Tamil MOVIE
  [3] Maanagaram | Must Watch MOVIE
  [4] Maanasthan | Tamil MOVIE
  [5] Maanagara Kaaval | Tamil MOVIE
> [6] Maanga | Tamil MOVIE
  [q] Exit!
  [s] Search Again!
  [d] Download!
  [p] Switch Provider!
  [sd] Download Whole Show!
```

I would like to see a command function like `s <movie title>` to search that title, `p <sflix>` to switch to that provider, which can reduce few steps.

**Comment by bachig26** [comment]
an addition to these, if possible like at the beginning `mov-cli english iron man` to invoke a provider in english providers to search for the defined title.

my idea is the ability to set a default provider in each catalog and requesting the results from them, like defining `english = sflix`, `asian = viewasian`, `indian = einthusan`, etc.

**Comment by bachig26** [comment]
maybe a local `config file` function to make commands and arguments to customize and be more rebost.

**Comment by ghost** [comment]
> **Describe the feature/change you'd like** add command functions to invoke the certain functions like search again, switch providers, etc.
> 
> example: from a search result
> 
> ```
>   [1] Maanaadu | Must Watch MOVIE
>   [2] Maanavan | Tamil MOVIE
>   [3] Maanagaram | Must Watch MOVIE
>   [4] Maanasthan | Tamil MOVIE
>   [5] Maanagara Kaaval | Tamil MOVIE
> > [6] Maanga | Tamil MOVIE
>   [q] Exit!
>   [s] Search Again!
>   [d] Download!
>   [p] Switch Provider!
>   [sd] Download Whole Show!
> ```
> 
> I would like to see a command function like `s <movie title>` to search that title, `p <sflix>` to switch to that provider, which can reduce few steps.

i don't even know if thats possable in fzf

**Comment by Poseidon444** [comment]
this support was present in the older version of mov-cli
it was something along the lines of
```mov-cli -p "<provider-here>" -q "<query-here>"```

**Comment by bachig26** [comment]
closing this as it exists and with last discussion #180 which i found them.
