### ISSUE TITLE
[BUG] gogoanime and the flix

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#109]
I think you forgot to put gogoanime in the fzf menu.

the flix seams dead.... Is the shell script dead too?

**Comment by ghost** [comment]
Yeah i added gogoanime with the latest update and theflix is dead and the Shell Script uses TheFlix so it's dead.

**Comment by pitsi** [comment]
Is theflix dead for everyone? I wanted to report it since Friday, but I thought it would be temporary or only on my end. It was not as it seems.

**Comment by ghost** [comment]
> Is theflix dead for everyone? I wanted to report it since Friday, but I thought it would be temporary or only on my end. It was not as it seems.

it is dead for everyone, i don't know if its becoming back or not

**Comment by pitsi** [comment]
Out of the many fmovies mirror/clone sites (theflix was one of them), can't we find one that works the same way like theflix did?
I mean... the token part was the most important part of the script as it seems, so changing the base_url variable should make it work again.
