### ISSUE TITLE
[BUG] kimcartoon no video 

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#110]
selecting videos works, but it can't get the video links.

```
  File "/usr/lib/python3/dist-packages/mov_cli/websites/kimcartoon.py", line 51, in cdn_url
    iframe_id = re.findall('''src="https://www.luxubu.review/v/(.*?)"''',res)[0]
IndexError: list index out of range
```

**Comment by preewo** [comment]
because they have changed from luxubu , to vidmoly.to and keephealth.info using sbface.com as storage... i've been trying to get the direct links in the past 24 hours , but it is not that simple as before ...
