### ISSUE TITLE
[BUG] The Current Key is not correct

### ISSUE THREAD

**Issue by umop3plsdn** [mov-cli/mov-cli#114]
decided to update since i would get unicode decode error every so often with 0.6.9 so i updated to 1.1.2 and now it's telling me that the Current Key is not correct please wait

**Comment by ghost** [comment]
well thats the unicode decode error but instead reporting the error it raises this text instead

**Comment by fearlessgeekmedia** [comment]
I'm having this issue after reinstalling this after switching Linux distros. What was done to fix this issue? Because I'm having it now.
