### ISSUE TITLE
status of the shell script?

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#116]
What's the long term status of the shell script? You haven't deleted it yet. I find it odd.

**Comment by pitsi** [comment]
They may be looking for another fmovies mirror (because that is what theflix really was) to replace it.

**Comment by Poseidon444** [comment]
yea

**Comment by pitsi** [comment]
How can I (= a simple user) help with that? What is the primary function of the script? I think that the part where it gets the token is the core of its functionality and the rest depend on that.

--edit
There are 3 other mirrors of fmovies among the supported sites of mov-cli but none of them works for the bash version :(

**Comment by ghost** [comment]
lobster is a shell alternative.
https://github.com/justchokingaround/lobster

You may want to drop the shell entirely.
If you want to maintain a shell  alternative on the side,then help maintaining lobster seams more appropriate, then having a shell scrip along side the python script.

**Comment by pitsi** [comment]
I know about lobster. I have written part of its documentation for its v3 update and I use the api it uses for a couple of my scripts. But unlike lobster which uses an api, mov-cli scrapes the web page in question.

**Comment by pitsi** [comment]
RIP shell script :'( 
https://github.com/mov-cli/mov-cli/commit/579a188c3da75faae80c5d3eda9b7f95d7865eb6

**Comment by ghost** [comment]
The end....
https://www.youtube.com/watch?v=ZeMlQEWEg2Q

For those looking for a shell alternative:
https://github.com/justchokingaround/lobster
