### ISSUE TITLE
None of the servers work in India(Movies)

### ISSUE THREAD

**Issue by jaivardhan-bhola** [mov-cli/mov-cli#118]

**Comment by R3tr0Ananas** [comment]
Try changing your DNS Settings. Something to like 1.1.1.1 or 8.8.8.8

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Jaivardhan Bhola ***@***.***>
Gesendet: Wednesday, February 8, 2023 9:12:46 AM
An: mov-cli/mov-cli ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [mov-cli/mov-cli] None of the servers work in India(Movies) (Issue #118)

**Comment by ghost** [comment]
Try changing your DNS Settings. Something to like 1.1.1.1 or 8.8.8.8

**Comment by jaivardhan-bhola** [comment]
Wlext error: Int has no len()

**Comment by jaivardhan-bhola** [comment]
Except that no other server works

**Comment by ghost** [comment]
> Wlext error: Int has no len()

should be fixed

**Comment by jaivardhan-bhola** [comment]
https://www.actvid.com/search/game-of-thrones
Error: [Errno 104] Connection reset by peer 
Please open an issue if this is not due due to your internet connection

**Comment by jaivardhan-bhola** [comment]
getting this now

**Comment by ghost** [comment]
> https://www.actvid.com/search/game-of-thrones Error: [Errno 104] Connection reset by peer Please open an issue if this is not due due to your internet connection

This is due to your Internet connection

**Comment by jaivardhan-bhola** [comment]
Any idea how to fix this?

**Comment by ghost** [comment]
2 Possable things whats happens is you are getting a tcp reset or a slow connection

**Comment by ghost** [comment]
Stale
