### ISSUE TITLE
[Function "gh_key" of actvid.py is fetching absurd data]

### ISSUE THREAD

**Issue by Shamim1977** [mov-cli/mov-cli#119]
**Function "gh_key" in file "cli/websites/actvid.py" is fetching absurd data**
The function essentially fetches a key from github with the follwoing url-
https://raw.githubusercontent.com/mov-cli/movkey/main/key.txt

but the data coming through is not right as it never works and in console we see the following error-
'utf-8' codec can't decode byte 0xee in position 2: invalid continuation byte

I am pretty sure the bot/system which updates the value at the above location at github is not perming right.
Please suggest what I can do.

**Comment by Shamim1977** [comment]
I tried minutes ago, it worked once, and now again this error-
'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte

**Comment by Shamim1977** [comment]
Even if I try it in console, I get the same error-
![image](https://user-images.githubusercontent.com/8396797/218321220-c33eaecf-7707-49f0-a7c9-be020e35ea1c.png)

**Comment by ghost** [comment]
https://github.com/mov-cli/movkey in this repo we are fetching newest key from this repo https://github.com/consumet/rapidclown and it's currently broken, not ours.

**Comment by Shamim1977** [comment]
Thanks for the clarification
