### ISSUE TITLE
[Bash version] Please add a way to limit or select the resolution

### ISSUE THREAD

**Issue by pitsi** [mov-cli/mov-cli#12]
The bash version of mov-cli, running on debian testing/unstable x64 and mpv (with vdpau as video output) as the player.

I am watching a series this week and today I noticed that the episode was too laggy from the start. Mpv's stats (the on screen info that comes up when pressing "i") showed that the video was an 4k (3840*2160, or 2160p) h265. Similar info was also displayed in the terminal like so

`Video link fetched 
https://urlhere.com/Something-S01E01-HDR.2160p.WEB.h265-blablabla`

Sadly, I have neither the bandwith, nor the hardware for such a stream, so a way to select the resolution (either via a switch or from some config file) is more than desirable. The same applies for the codec and hdr.

Thank you in advance :)

**Comment by Poseidon444** [comment]
Sadly the sh version is limited the one provider for now, we are planning to add more providers: yes the website has only one resolution

**Comment by brianalvarezv** [comment]
You can limit FPS and resolution in MPV config file. Same on VLC

**Comment by pitsi** [comment]
Can you please show me how? This is (part of) my mpv.conf if it helps
```
$ cat .config/mpv/mpv.conf 
vo=vdpau,xv
hwdec=vdpau
ao=alsa
sub-codepage=iso-8859-7
sub-font=Tahoma
sub-font-size=48
#sub-bold=yes
stop-screensaver=yes
cache=auto
audio-display=no

#ytdl-format=bestvideo[height<=?720]+bestaudio/best
ytdl-format=bestvideo[height<=?720][vcodec!=vp9]+bestaudio/best
```
