### ISSUE TITLE
[BUG] click module not included in requirments.txt

### ISSUE THREAD

**Issue by amonull** [mov-cli/mov-cli#120]
**Describe the bug**
trying to run mov-cli without click installed results in error

**Expected behavior**
mov-cli runs without any problems

**Screenshots**
![image](https://user-images.githubusercontent.com/90932550/218806797-69d4bce0-05dc-441c-a388-887b87422728.png)

**Error**
```
Traceback (most recent call last):
  File "/home/amon/.local/bin/mov-cli", line 5, in <module>
    from mov_cli.__main__ import movcli
  File "/home/amon/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/__init__.py", line 1, in <module>
    from . import __main__
  File "/home/amon/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/__main__.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'

```

**Desktop (please complete the following information):**
 - OS: void linux x86_64
 - pip-version: 23.0
 - py-version: 3.11.2
 - kernel-version: 6.1.11_1

**Additional context**
mov-cli installed through pipx to create its own virtual environment to isolate it, before updating to 1.1.5 this issue did not exist and after installing click running the command `pipx runpip mov-cli install click` the problem stopped.
click should be added to requirments.txt to avoid this issue.

**Possible cause**
click not listed inside requirments.txt

**Possible solution**
adding click>=8.1.3 (latest click version) to requirments.txt

**Version**
1.1.7

**Comment by ghost** [comment]
This issue has been fixed.
