### ISSUE TITLE
[BUG] Not able to upgrade mov-cli

### ISSUE THREAD

**Issue by CliveKBinu** [mov-cli/mov-cli#121]
**Describe the bug**
Not able to upgrade mov-cli, when using pip install mov-cli --upgrade. I am receiving **error: subprocess-exited-with-error** 

**Expected behavior**
Able to upgrade without error

**Screenshots**
<img width="596" alt="image" src="https://user-images.githubusercontent.com/63173077/219707652-74c88a2c-5508-444d-8fce-b391be879d17.png">

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by ghost** [comment]
try:
pip install krfzf-py
and then
pip install mov-cli

**Comment by CliveKBinu** [comment]
> try: pip install krfzf-py and then pip install mov-cli

 I already tried this before posting this issue, But I saw u uploaded a new release and tried pip install mov-cli --upgrade and it worked.

Thanks for the help 😁
