### ISSUE TITLE
[FEATURE] porn providers in a sister project

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#125]
They were some porn providers, then they were removed.

If this is such a big problem that they can't be included, i'm proposing the creation of a separate module with all the xxx stuff. People that want them, just need to install the extra module. Maybe named something like mov-cli-xxx, or more general mov-cli-offensive.

**Comment by bachig26** [comment]
> They were some porn providers, then they were removed.
> 
> If this is such a big problem that they can't be included, i'm proposing the creation of a separate module with all the xxx stuff. People that want them, just need to install the extra module. Maybe named something like mov-cli-xxx, or more general mov-cli-offensive.

it's already a separate package: https://github.com/mov-cli/porn-cli

please close this issue.

**Comment by ghost** [comment]
ah... lol
They didn't announce it...
