### ISSUE TITLE
Scdn Sports Provider doesn't work[BUG]

### ISSUE THREAD

**Issue by ttx99** [mov-cli/mov-cli#126]
**Describe the bug**
Scdn Sports provider doesnt work

**Screenshots**
![Screenshot_2023-03-06_04-07-03](https://user-images.githubusercontent.com/95531944/222983270-a568c494-aab8-4298-aece-8c350071f1ac.png)

**Error**
* Attach Screenshots or Terminal output
![Screenshot_2023-03-06_04-07-03](https://user-images.githubusercontent.com/95531944/222983277-9f1c3674-550d-43d3-be68-c0b000e17a25.png)

**Desktop (please complete the following information):**
Linux

**Version**
1.3.1

**Comment by ttx99** [comment]
Okay for some reason only link 1 works all the time.

Since the scdn provider uses sportsurge.club link and only the 1st link work (I only tested this with nba) which is 1stream.eu pls delete the whole scdn provider and add this instead it's more stable 1stream instead?
 or start with nba only first since the season and playoffs run till June https://1stream.eu/nbastreams so it can be properly tested.

**Comment by Poseidon444** [comment]
Will look into it

**Comment by ttx99** [comment]
this is also an nba live stream link that provides excellent quality 60fps https://crackstreams.biz/nbastreams/
