### ISSUE TITLE
[BUG] turkish123 can't display episodes

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#127]
**Describe the bug**
`turkish123` can't display the episodes, not sure why.

**Expected behavior**
displays the episodes list.

**Screenshots**

https://user-images.githubusercontent.com/96393348/223499974-eadb6da9-855f-4478-bb34-db59c475c408.mp4

**Error**
```
https://turkish123.a/
Error: [Errno 11001] getaddrinfo failed
 Please open an issue if this is not due due to your internet connection
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.3.1

**Comment by bachig26** [comment]
@R3tr0Ananas it's fetching wrong extension (`.a` instead of `.ac`) when opening the title, i looked the codes, as far i know it looks same with the site.

**Comment by ghost** [comment]
That's the providers issue as the show's link is just https://turkish123.a

![grafik](https://user-images.githubusercontent.com/83706294/223526547-f15a5901-8f70-4219-a85c-ea52f5695ad1.png)
