### ISSUE TITLE
Kimcartoon

### ISSUE THREAD

**Issue by preewo** [mov-cli/mov-cli#132]
It seems kimcartoon.li has changed there location for links for sbface.com, keephealthy.info and vidmoly.to instead of luxubu.review... so now it's harder to get the links.
I am trying it with a headless selenium but that's a waste of time .
Any fox soon ?

**Comment by ghost** [comment]
Yeah there will be a fix, @Poseidon444 is working on it.

**Comment by Poseidon444** [comment]
I'll be changing the provider

**Comment by preewo** [comment]
I've been working on scraping kimcartoon entirely. Now I have to come up with a workaround again. Check my repo there's a sqlite db filled up completely yesterday.

**Comment by Poseidon444** [comment]
alright
