### ISSUE TITLE
Subtitles support?

### ISSUE THREAD

**Issue by 097115** [mov-cli/mov-cli#14]
May be somehow incorporate [subliminal](https://github.com/Diaoul/subliminal)? Or add subs in some other way? 

Would be a great addition :)

**Comment by Poseidon444** [comment]
This looks pretty cool, i'll look into it

**Comment by 097115** [comment]
Also, a small side note: some movies and / or tv shows are already hosted with subtitles (like [this](https://sflix.se/watch-tv/watch-twin-peaks-hd-39237.4920997), for example, has a whole bunch of various captions added -- and even if one presses that yellow 'Download' button, they [seem to be available there](https://i.imgur.com/Ty56uaN.png), too). 

Would be great somehow to access those, may be? :)

**Comment by Poseidon444** [comment]
We can access them, but without knowing the language of subtitles you prefer, we'll have to load all the languages; impacting the performance so we are working on a config file

**Comment by 097115** [comment]
> we are working on a config file

So that we would be able to specify the preferred languages in it? Sounds super cool, thanks!
