### ISSUE TITLE
[BUG] The Current Key is not correct, please wait.

### ISSUE THREAD

**Issue by fkingrumpy** [mov-cli/mov-cli#143]
**Describe the bug**
Unable to watch anything using any English providers. Have not tested other languages.

**Expected behavior**
An episode of Star Trek to play. 

**Error**
[!] What would you like to watch: star trek
https://www.actvid.com/search/star-trek
https://www.actvid.com/ajax/v2/tv/seasons/38753
https://www.actvid.com/ajax/v2/season/episodes/5854
https://www.actvid.com/ajax/v2/season/episodes/5854
https://www.actvid.com/ajax/v2/episode/servers/133140/#servers-list
https://www.actvid.com/ajax/get_link/4995709
https://dokicloud.one/embed-4/ekcbCYJaoPTj?z=
https://dokicloud.one/ajax/embed-4/getSources?id=ekcbCYJaoPTj
https://raw.githubusercontent.com/mov-cli/movkey/main/key.txt
[!] The Current Key is not correct, please wait.

[!] What would you like to watch: star trek
https://sflix.se/search/star-trek
https://sflix.se/ajax/v2/tv/seasons/38753
https://sflix.se/ajax/v2/season/episodes/5854
https://sflix.se/ajax/v2/season/episodes/5854
https://sflix.se/ajax/v2/episode/servers/133140/#servers-list
https://sflix.se/ajax/get_link/4995709
https://dokicloud.one/embed-4/ekcbCYJaoPTj?z=
https://dokicloud.one/ajax/embed-4/getSources?id=ekcbCYJaoPTj
https://raw.githubusercontent.com/mov-cli/movkey/main/key.txt
[!] The Current Key is not correct, please wait.

[!] What would you like to watch: star trek
https://solarmovie.pe/search/star-trek
https://solarmovie.pe/ajax/v2/tv/seasons/38753
https://solarmovie.pe/ajax/v2/season/episodes/5854
https://solarmovie.pe/ajax/v2/season/episodes/5854
https://solarmovie.pe/ajax/v2/episode/servers/133140/#servers-list
https://solarmovie.pe/ajax/get_link/4995709
https://dokicloud.one/embed-4/ekcbCYJaoPTj?z=
https://dokicloud.one/ajax/embed-4/getSources?id=ekcbCYJaoPTj
https://raw.githubusercontent.com/mov-cli/movkey/main/key.txt
[!] The Current Key is not correct, please wait.

[!] What would you like to watch: star trek
https://dopebox.to/search/star-trek
https://dopebox.to/ajax/v2/tv/seasons/38753
https://dopebox.to/ajax/v2/season/episodes/5854
https://dopebox.to/ajax/v2/season/episodes/5854
https://dopebox.to/ajax/v2/episode/servers/133140/#servers-list
https://dopebox.to/ajax/get_link/4995709
https://dokicloud.one/embed-4/ekcbCYJaoPTj?z=
https://dokicloud.one/ajax/embed-4/getSources?id=ekcbCYJaoPTj
https://raw.githubusercontent.com/mov-cli/movkey/main/key.txt
[!] The Current Key is not correct, please wait.

With remove stream there's a different error:

https://remotestre.am/e/?tmdb=655&s=5&e=16
Traceback (most recent call last):
  File "/usr/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/__main__.py", line 63, in movcli
    provider.redo()  # if result else provider.redo(query)
    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 249, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 240, in display
    self.TV_PandDP(mov_or_tv, "p")
  File "/usr/lib/python3.11/site-packages/mov_cli/websites/remotestream.py", line 115, in TV_PandDP
    url = self.cdn_url(t[self.aid], season, episode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/websites/remotestream.py", line 81, in cdn_url
    file = re.findall('"file":"(.*?)"', res)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Desktop (please complete the following information):**
Arch Linux

**Additional context**
I originally installed through AUR but after checking your git again, I noticed that it wasn't listed under the installation section. So, thinking it may not be maintained; I installed it through pip and encountered the same errors. Which lead me to check the AUR version and noted that it was the latest version.

**Possible cause**
If you have a hunch on what might be causing this, please add it here.

**Possible solution**
If you know a way we could fix this, please add it here.

**Version**
1.3.8

**Comment by ananasmoe** [comment]
Should be fixed with the upcoming update.

**Comment by ananasmoe** [comment]
is fixed
