### ISSUE TITLE
[FEATURE] iOS support

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#144]
**Describe the feature/change you'd like**

I just came across the ani-cli and they worked out to support for iOS via iSH (shell tool), if possible I would like to see iOS support comes to mov-cli.

**Additional context**

https://github.com/pystardust/ani-cli#ios

[core iOS support PR to ani-cli] https://github.com/pystardust/ani-cli/pull/1105

[iOS download support PR to ani-cli] https://github.com/pystardust/ani-cli/pull/1112

**Comment by Poseidon444** [comment]
We need maintainers, currently we have no maintainers

**Comment by ananasmoe** [comment]
Currently being developed.

**Comment by bachig26** [comment]
added in https://github.com/mov-cli/mov-cli/commit/0c3dbca1f3d2411913806f08a2b83c902dee39ac
