### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Migi001** [mov-cli/mov-cli#145]
**Describe the bug**
I can't play almost any request I ask, I tried different providers, just Asian and Anime work, sometimes English providers->remotestream works, but not all the time, everything else send me error: Current key is not correct or Time out, in some cases list index out of range.

**Expected behavior**
For example Indiana Jones Cyrstal Skull
[!] What would you like to watch: indiana
https://sflix.se/search/indiana
https://sflix.se/ajax/movie/episodes/19153
https://sflix.se/ajax/get_link/5349502
https://dokicloud.one/embed-4/STybjtjWYJBk?z=
https://dokicloud.one/ajax/embed-4/getSources?id=STybjtjWYJBk
https://raw.githubusercontent.com/mov-cli/movkey/main/key.txt
[!] The Current Key is not correct, please wait.

Dune
https://www.themoviedb.org/search/tv?query=dune&language=en
https://www.themoviedb.org/search/movie?query=dune&language=en
['Dune', 'Dune', 'Dune', 'Woman in the Dunes', 'Sexual Chronicles of a French Family', 'Sinner: The Secret Diary of a Nymphomaniac', 'Dune: Part Two', 'The Dunes', 'The Dune', 'The Dunes', 'On the Dune of Solitude', 'The House on the Dune', 'The House on the Dune', "Jodorowsky's Dune", 'Devil In Dune', 'Diary of a Fleeting Affair', 'Dunechka', 'Dune Drifter', 'Diary of a Chambermaid', 'Diary of a Chambermaid', 'Long Road in the Dunes', "Frank Herbert's Dune", "Frank Herbert's Children of Dune", "Le temps d'une paix", 'Crossroads', 'Dünentod – Ein Nordsee-Krimi', 'Dune: The Sisterhood', "L'appel d'une vie", 'H24 - 24 Hours, 24 Women, 24 Stories', "Les chroniques d'une mère indigne", 'Vintage Curves of Cuba', "Le temps d'une histoire", "Les derniers jours d'une icône", "États-Unis, histoire d'une nation", "À la conquête d'une maison", 'Histoires d’une nation', "Les Coulisses d'une création originale", "Sinatra : Le parcours d'une légende", "Jésus, l'histoire d'une Parole", "Europe, dans les coulisses d'une décennie de crise", 'Dune Collection', 'The Princess Diaries Collection', 'Legally Blonde Collection']
https://remotestre.am/e/?tmdb=841
Traceback (most recent call last):
  File "/home/m/.local/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/__main__.py", line 63, in movcli
    provider.redo()  # if result else provider.redo(query)
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/utils/scraper.py", line 249, in redo
    return self.display(search, result)
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/utils/scraper.py", line 160, in display
    return self.redo()
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/utils/scraper.py", line 249, in redo
    return self.display(search, result)
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/utils/scraper.py", line 160, in display
    return self.redo()
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/utils/scraper.py", line 249, in redo
    return self.display(search, result)
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/utils/scraper.py", line 242, in display
    self.MOV_PandDP(mov_or_tv, "p")
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/websites/remotestream.py", line 103, in MOV_PandDP
    url = self.cdn_url(m[self.aid])
  File "/home/m/.local/lib/python3.10/site-packages/mov_cli/websites/remotestream.py", line 81, in cdn_url
    file = re.findall('"file":"(.*?)"', res)[0]
IndexError: list index out of range

As you can see doesn't work, maybe I messed up somewhere sorry I'm new in this world. Hope can you can give me some instructions how to fix it

**Comment by ghost** [comment]
I did a hack, i'm not using the normal application. But i'm getting also:
`[!] The Current Key is not correct, please wait.`

**Comment by ananasmoe** [comment]
So for RemoteStream if you get an IndexError it just means the Movie or Show is not on Remotestreams Server. The Current Key problem is fixed after the upcoming update.

**Comment by ananasmoe** [comment]
should be fixed
