### ISSUE TITLE
[BUG] Python errors when upgrading to the latest version from AUR

### ISSUE THREAD

**Issue by fkingrumpy** [mov-cli/mov-cli#147]
**Describe the bug**
Python errors appear during upgrade/fresh installation using yay

**Expected behavior**
Yay to progress without errors

**Screenshots**
NA

**Error**
==> Making package: mov-cli-git 1.3.8.r596.6d05915-3 (Tue 23 May 2023 22:01:51 BST)
==> Retrieving sources...
  -> Updating mov-cli git repo...
==> Validating source files with md5sums...
    mov-cli ... Skipped
:: (1/1) Parsing SRCINFO: mov-cli-git
==> Making package: mov-cli-git 1.3.8.r596.6d05915-3 (Tue 23 May 2023 22:01:51 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating mov-cli git repo...
==> Validating source files with md5sums...
    mov-cli ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of mov-cli git repo...
Cloning into 'mov-cli'...
done.
==> Starting pkgver()...
==> Updated version: mov-cli-git 1.3.8.r609.e99c08a-1
==> Sources are ready.
==> Making package: mov-cli-git 1.3.8.r609.e99c08a-1 (Tue 23 May 2023 22:01:53 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
* Getting build dependencies for wheel...
* Building wheel...
Successfully built mov_cli-1.4.1-py3-none-any.whl
==> Entering fakeroot environment...
==> Starting package()...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/usr/lib/python3.11/site-packages/installer/__main__.py", line 86, in _main
    with WheelFile.open(args.wheel) as source:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/installer/sources.py", line 162, in open
    with zipfile.ZipFile(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zipfile.py", line 1283, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/aaron/.cache/yay/mov-cli-git/src/mov-cli/dist/mov_cli-1.3.8-py3-none-any.whl'
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: mov-cli-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
mov-cli-git - exit status 4

**Desktop (please complete the following information):**
Arch Linux

**Additional context**
NA

**Possible cause**
NA

**Possible solution**
NA

**Version**
1.3.8.r596.6d05915-3

**Comment by ananasmoe** [comment]
@Poseidon444

**Comment by Poseidon444** [comment]
I'll look into and update the issue if I find anything helpful

**Comment by CheesyChocolate** [comment]
aur get the version from git head (1.3.8.r618.f584236)

package that build with python build command will output a different version (mov_cli-1.4.2)

so the the following line of aur PKGBULD will fail
```
 python -m installer --destdir="$pkgdir" \
                "$srcdir/${pkgname%-git}/dist/${_pkgname/-/_}-${pkgver%.r*}-py${_py##* }-none-any.whl"
```
this line expects to see a file with name `mov_cli-1.3.8-py3-none-any.whl`

but what actually exist there is `mov_cli-1.4.2-py3-none-any.whl`

so I guess @Poseidon444 need to do a `git tag -a "v1.4.2" -m "bump version to v1.4.2`

and I don't know if aur maintainer for package need to update `pkgver=1.3.8.r618.f584236` manually or it happens automagically

**Comment by Poseidon444** [comment]
Thank you for submitting a possible solution, I will look into it

**Comment by ghost** [comment]
porn-cli has the same ptoblem

**Comment by CheesyChocolate** [comment]
unlike what I originally assumed 
there is nothing needed to do by developer 
the AUR package maintainer need to update version of package.
I have already made a [comment](https://aur.archlinux.org/packages/mov-cli-git#comment-920259)

**Comment by anakojm** [comment]
Fixed https://aur.archlinux.org/cgit/aur.git/commit/?h=mov-cli-git&id=fab8e999b56999d8ecce027febfac6c4ba5ef4e0
Thanks for the comment

**Comment by ananasmoe** [comment]
Great.

This issue should be now resolved.
