### ISSUE TITLE
Can we have just a .Config file instead of selecting server every time in Python version?

### ISSUE THREAD

**Issue by ttx99** [mov-cli/mov-cli#15]
default server: solarmovie.pe
default player: mpv
default download directory: /Downloads
default quality:  1080p

or can we have just a numbered list of server and select by number:
[1] actvid
[2]theflix
[3]sflix
[4]solar

but I prefer the .config file for efficiency cause you will find that some servers are faster or slower for you.

**Comment by Poseidon444** [comment]
I am working on this.

**Comment by ghost** [comment]
Provider: #36 
Download: #45
