### ISSUE TITLE
[FEATURE] Support for vlc

### ISSUE THREAD

**Issue by shinysocks** [mov-cli/mov-cli#155]
- could we please get support for vlc?

**Comment by shinysocks** [comment]
Nevermind, mpv is clearly the superior choice... Can you add in either an option to use the `--no-keepaspect-window` flag or use this by default as otherwise mpv windows look odd on a tiling window manager.

**Comment by ananasmoe** [comment]
Will be readded in the rewrited mov-cli.

**Comment by shinysocks** [comment]
cool!
