### ISSUE TITLE
[BUG] 'binascii.Error: Incorrect padding' for all providers

### ISSUE THREAD

**Issue by AdityaRoot** [mov-cli/mov-cli#158]
**Describe the bug**
A clear and concise description of what the bug is. Explain the steps that you took leading up to the bug to help aid in recreating it.

After searching on a provider, which works as intended - once I select any movie or TV show I receive the following error: `binascii.Error: Incorrect padding`

I have confirmed that my system and mov-cli are up to date, and that ani-cli works as intended.C

**Expected behavior**

For the mpv player to start as normal.

**Error Screenshots**
![image](https://github.com/mov-cli/mov-cli/assets/66115252/5a2e108a-d6fa-4b32-a612-381cfe7d1e19)

**Desktop (please complete the following information):**
Arch Linux

**Possible cause**
I am unsure but I am presuming it might be something due to my personal python install? As I do not see any other reports of this issue on the github.

I also receive this warning while using pip, I am unsure if it is relevant
```DEPRECATION: Loading egg at /usr/lib/python3.11/site-packages/lensfun-0.3.4-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..```

**Version**
mov-cli version 1.4.5
mpv 1:0.35.1-8
ffmpeg 2:6.0-8
ffmpeg4.4 4.4.4-1
lxml version 4.9.2

Thank you!

**Comment by MrLDasVino** [comment]
I am having the same issue

**Comment by ananasmoe** [comment]
Well the Hoster (Dokicloud) has changed something. We are working on it.

**Comment by EbanNox** [comment]
Had the same issue, and so was my frend whom i provided movcli to. We are all experiansing the same issue, I thought that the issue is the Web site scrapers are out dated :(

**Comment by ananasmoe** [comment]
Fixed
