### ISSUE TITLE
Feature request add command for searching latest and trending movies/tv show.

### ISSUE THREAD

**Issue by ttx99** [mov-cli/mov-cli#16]
Mov-cli: (select server/provider) Solar
Mov-cli:  -T  --trending (displays the trending movie/tvshows)  or -L --latest  (displays the latest movie/tvshows)

Cause sometimes we just don't know what to watch  and we need to browse contents that might interest us.

**Comment by Poseidon444** [comment]
Seems like a good feature to add

**Comment by ghost** [comment]
#41
