### ISSUE TITLE
[BUG] in linux config files just dumped in home

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#164]
at the very least you should put them in a folder, not just dump them like that. Bad dev, baaad.

There's the xdg standard in linux for files in home.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

In short:

> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.
> 
> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
> 
> $XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

specifically for mov-cli, you only care about config. You put your config files in $XDG_CONFIG_HOME/mov-cli ,if $XDG_CONFIG_HOME doesn't exist, you put them in $HOME/.config/mov-cli . This folder is for configurations, that can be recreated moderately  easily.

the cache is for stuff that are easily recreated automatically, like for example logs. The data folder is for user generated data that can't be recreated easily, like for example history.

**Comment by ananasmoe** [comment]
added in 1.4.7
