### ISSUE TITLE
[BUG]An Exception has occurred | Incorrect padding

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#165]
Hey guys 
I recently updated to mov-cli==1.4.6.
It works well until the point where I am supposed to get the link playing on mpv.
As mentioned I use mpv as my player.
Python version 3.11.3
Desktop Arch Linux
kernel version 6.4.5-arch1-1

[18:53 ~_$] mov-cli
[!] What would you like to watch: modern family
https://sflix.se/search/modern-family
https://sflix.se/ajax/v2/tv/seasons/39507
https://sflix.se/ajax/v2/season/episodes/374
https://sflix.se/ajax/v2/episode/servers/6786/#servers-list
https://sflix.se/ajax/sources/4858219
https://dokicloud.one/embed-4/4risnNJVPYQI?z=
https://dokicloud.one/ajax/embed-4/getSources?id=4risnNJVPYQI
https://raw.githubusercontent.com/enimax-anime/key/e4/key.txt
[!] An Exception has occurred | Incorrect padding

I have no clue what causes this error of Incorrect padding

**Comment by ananasmoe** [comment]
already a open issue: #158
