### ISSUE TITLE
[BUG] linux, crash on first run

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#166]
on first run it fails to find `.config/mov-cli/provider.mov-cli` but it somehow generated it before the crash. So on second run it works fine.

~~also i don't see lang.mov-cli , maybe an other error?~~

**Comment by ghost** [comment]
there's something similar with `lang.mov-cli` at first it throws an error and it works on the second try

**Comment by EbanNox** [comment]
Its the same behaviur on android and Windows, but in my case it seems more permanent,  every time i run mov-cli it throws back the same error over and over. atm the current version of mov-cli 1.4.7 is un runnable

**Comment by ghost** [comment]
the difference could be the different python versions.
if you move the files at the expected place, it should just work.

**Comment by ghost** [comment]
I think that in your case it fails completely, because it's trying to generate the linux folders.

**Comment by 4cecoder** [comment]
i just made 2 PR's that should fix this bug

https://github.com/mov-cli/mov-cli/pull/223
&
https://github.com/mov-cli/mov-cli/pull/222

**Comment by 4cecoder** [comment]
I've updated this issue and should be fixed in the latest v3 branch.
