### ISSUE TITLE
[Provider] watchseries.id

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#168]
**Website**

Website: https://watchseries.id/

**Extras**

Has a well managed community aswell that do add a bunch on their end, would be good to add this to mov-cli as a provider, pls consider

**Comment by EbanNox** [comment]
Would categorize it as English provider , but u make the decision on that

**Comment by Poseidon444** [comment]
👍

**Comment by ananasmoe** [comment]
WatchSeries has the url for the Streaming Service encrypted.
