### ISSUE TITLE
UX (bash)

### ISSUE THREAD

**Issue by brianalvarezv** [mov-cli/mov-cli#17]
Maybe you could ask the users if they want to search movies or tv-shows, instead of having movies as default and tv-shows "hidden". 
Besides, when searching (i.g.: "Select episode" step) it would be nice to have an option to restart the program without quitting. For now, if you decide you want to search another show, you have to close the program and open it again.

**Comment by brianalvarezv** [comment]
Still with TV-shows issue here. If you don't put -t option on, program will just search for movies. I've cloned the repo in my Linux machine just two days ago and the issue persisted

**Comment by CoolnsX** [comment]
The reason for -t argument is cause the url of searching TV and movies is different.. i will take ur suggestion into consideration..

**Comment by brianalvarezv** [comment]
> The reason for -t argument is cause the url of searching TV and movies is different.. i will take ur suggestion into consideration..

I understand. So, may I suggest a simple workaround... When the user launches the program, it could ask him "What do you wanna watch?" a) Movies b) TV Shows, and that's it. So the url problem is bypassed, and no manual commands are needed

Excuse my lack of English

**Comment by ghost** [comment]
> The reason for -t argument is cause the url of searching TV and movies is different.. i will take ur suggestion into consideration..

Will this be added or should i close this issue @CoolnsX?
