### ISSUE TITLE
AUR and MPR PKGBUILDS

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#171]
there's this in the AUR
https://aur.archlinux.org/packages/mov-cli-git
and these in the mpr
https://mpr.makedeb.org/packages/mov-cli
https://mpr.makedeb.org/packages/mov-cli-git

it would be nice to mention them in the README.

**Comment by Poseidon444** [comment]
👍

**Comment by ghost** [comment]
you could also mention the optional porn-cli
the corresponding PKGBUILD in the MPR, it's not in the AUR 
https://mpr.makedeb.org/packages/python3-porn-cli

**Comment by ananasmoe** [comment]
They are now mentioned in the readme.
