### ISSUE TITLE
[BUG] strange scraper bug

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#175]
**Describe the bug**
A clear and concise description of what the bug is. Explain the steps that you took leading up to the bug to help aid in recreating it.
--
for some reason trying to watch jujutsu kaisen season 1 episode 7 on gogoanime provider prodused this in the console: [Check the file attachment that contains the console output]

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version: 22H2

**Version**
mov-cli 1.5.1

[ATTATCHMENT]
[mov-cli151err.txt](https://github.com/mov-cli/mov-cli/files/12270516/mov-cli151err.txt)

**Comment by EbanNox** [comment]
It just printed a entire html code on terminal. Very strange

**Comment by bachig26** [comment]
> It just printed a entire html code on terminal. Very strange

it usually prints the output in console, there's no issue in that, but with the issue on not playing might be related to the token key (not 100% sure on the error).
