### ISSUE TITLE
[BUG] key issue: English Proviers doesn't work

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#177]
**Describe the bug**
I think there is something wrong with key, i'm not sure but there might be possibility that the key has been changed to a different length.

**Expected behavior**
work as expected.

**Error**
```
[!] An Exception has occurred | 
Invalid base64-encoded string: number of data characters (537) cannot be 1 more than a multiple of 4
```
**Desktop (please complete the following information):**
 - OS: Windows 10 2H22
 - Version: 1.5.1

**Comment by bachig26** [comment]
@HLOAnanas also i think remotestream seems to have some issue, it's not well working as past week when i used. i might be wrong, but not sure.

**Comment by ananasmoe** [comment]
I have found a way to decrypt them, so a update will be on its way.

**Comment by ananasmoe** [comment]
Fixed
