### ISSUE TITLE
[FEATURE] possible word wrap in iSH

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#179]
**Describe the feature/change you'd like**
I just saw this that the word doesn't wrap when it goes over the display.

**Screenshot**

![IMG_6872](https://github.com/mov-cli/mov-cli/assets/96393348/d4cbe239-19df-481a-86f9-1a3f6b6fb009)

**Comment by ananasmoe** [comment]
We can't as fzf is a separate tool but you can adjust the font size in iSH.
