### ISSUE TITLE
updateProvider in select.py

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#180]
**Question**

@HLOAnanas can you check if this is working or just the code is idealing here?
https://github.com/mov-cli/mov-cli/blob/7a2d65b1505138eff9abb8a67fc2729d3118898b/mov_cli/utils/select.py#L154

because if it works we don't need to manually update the domain.

**Comment by ananasmoe** [comment]
It only works when using 'mov-cli --pupdate'
