### ISSUE TITLE
[BUG] 1.5.2 on android

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#181]
**Describe the bug**
The latest version of mov-cli 1.5.2 is completely boken on android. Where Version 1.5.1 worked smothly without any issue after reinstalling mov-cli 1.5.1 with pip3 instead of pip, where mov-cli 1.5.1 is completely brokes aswel If installera using regular pip, but anyways, mov-cli 1.5.2 not runnable on android...

**Expected behavior**
Smooth run

**Error**
Output on terminal:
------
~ $ mov-cli
/home/u0_a427/storage/mov-cli                        Traceback (most recent call last):                     File "/data/data/com.termux/files/usr/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())                                            ^^^^^^^^                                  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/__main__.py", line 12, in movcli                                                      cl, url = ask(CMD_ARGS.p)                                      ^^^^^^^^^^^^^^^                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/select.py", line 117, in ask
    calls = p()                                                  ^^^                                        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/select.py", line 90, in p                                                       firstStart()                                       File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/props.py", line 23, in firstStart                                               mkdir(home())
FileNotFoundError: [Errno 2] No such file or directory: '/home/u0_a427/storage/mov-cli'
------

**Desktop (please complete the following information):**
 - model: Samsung Galaxy S21 Ultra 5G (SM-G998B/DS)
 - OS: android 13
 - One UI: 5.1
 - Version: 13 , baseband version: G998BXXU6EWAF

**Comment by ananasmoe** [comment]
Try again with the new update.
