### ISSUE TITLE
Add -c / --choice and make prompt pre-select for faster UX.

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#182]
**Describe the feature/change you'd like**

after the last discussion on my question on the provider update #180 and going through the [init](https://github.com/mov-cli/mov-cli/blob/v3/mov_cli/__init__.py), which I didn't see before and it was really helpful in fast search and access.

with that i want to ask if it's possible to add more similar set of args for example like: 
1. accessing the content to play directly.
2. in case of tv shows or series, an addition arg to jump to a particular season or episode.

**Comment by bachig26** [comment]
also an possibility to have an arg for selecting the lang in the provider like einthusan where we need to choose a language like tamil, hindi, etc. after the entering the search term.
for this if we have an arg like `-lang` or `-l` to go with.
@HLOAnanas for example: `mov-cli -p einthusan -s beast -lang tamil`

**Comment by THEGOLDENPRO** [comment]
Will be adding this to v4 too.

**Comment by THEGOLDENPRO** [comment]
Some of what you described has already been added to v4 but it's not there yet in my opinion.

I want to be able to search, select and play for example "nyan cat" from YouTube with a single command like so:
```sh
mov-cli -c 1 nyan cat
```

This will require us to introduce a new cli argument like ``-c`` and ``--choice`` to preselect search results.

And to make things even faster the prompt function should preselect for you if there's only a single choice to choose from.
