### ISSUE TITLE
can't access other providers when when session/provider started using arg

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#184]
**Describe the bug**
when starting a session using the [args](https://github.com/mov-cli/mov-cli/blob/v3/mov_cli/__init__.py) for example: `mov-cli -p turkish123 -s 'Gencligim Eyvah'`

_**as you can see in the clip below, if the arg is used when opening a mov-cli session, it becomes sandboxed and can't jump to other providers and only able to work with that particular provider.**_

also as you have seen at the end of the clip, when I clicked the `Switch Provider`, it also reverts to the original search as that was used to create the session ` -s 'Gencligim Eyvah'`.

**Expected behavior**
able to switch between providers even when a session opened via args.

**Screenshots**

https://github.com/mov-cli/mov-cli/assets/96393348/81c33425-c0e8-4514-97cb-557932182fce

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.5.3

**Comment by ananasmoe** [comment]
Fixed
