### ISSUE TITLE
add domain checker and providers too

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#185]
**Describe the feature/change you'd like**
currently the mov-cli providers have the [domain update checker](https://github.com/mov-cli/mov-cli/blob/5f0ec5a69d37b286966d39b6596b3b76d5302387/mov_cli/utils/select.py#L154) when using `mov-cli --pupdate`, but this doesn't also check for the pron-cli providers.

It would be nice to have the provider checker for them too.

**Comment by THEGOLDENPRO** [comment]
V4 has significantly improved things and I don't think it would be possible or viable to implement this in v4. 

If a domain changes it's up to the plugin creator to change it then push an update.
