### ISSUE TITLE
add `Exit` and `Back` option in certain selection menu

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#186]
**Describe the feature/change you'd like**

sometimes I want to exit or go back respectively either to a different program or different providers but there is no exit or back option to do that.

@HLOAnanas **_if we have these two options `Exit` and `Back` option, it'll be a nice addition and helps ease of moving around with the mov-cli without exiting the session or in case of iSH, you need to completely close the app and reopen the app to do that which makes it more annoying._**

**Screenshot**
| 1. Main Providers selection menu      | 2. Website selection menu |
| ----------- | ----------- |
| ![IMG_0603](https://github.com/mov-cli/mov-cli/assets/96393348/132afa75-30f2-43e8-8168-d8397f31b193)      | ![IMG_0604](https://github.com/mov-cli/mov-cli/assets/96393348/5d763b1c-7437-4728-a32f-2e54089dbccc)       |

**Comment by THEGOLDENPRO** [comment]
Okay I'll add this to v4

**Comment by THEGOLDENPRO** [comment]
Can you try out mov-cli V4 and state if this is still an issue. The menus have significantly reduced in v4 (in fact the menu is just a fallback now you don't usually use it) so I can't see why a back button would be necessary now.

**Comment by bachig26** [comment]
> Can you try out mov-cli V4 and state if this is still an issue. The menus have significantly reduced in v4 (in fact the menu is just a fallback now you don't usually use it) so I can't see why a back button would be necessary now.

i think the back button is still a necessary thing to the mov-cli even in v4, with the watch options, there may be little flexibility to it.
but when you're in the search result section like the season lists, episode lists, you need to have an back button/option to go back if the user needs to explore different seasons or different search results.
as you know, if i entered into a season (say season 1), then there's no way to go back. i need to exit the mov-cli and re-enter the command to search again.

please take a look at this. @THEGOLDENPRO

**Comment by THEGOLDENPRO** [comment]
I'm not going to work on this but I'll accept a good pull request.

I think this problem can be solved if the cli options `-c` and `-ep` were used. The episode selector and watch options are just fallbacks to the command line. It's the command line that brings flexibility.

Implementing watch options was already quite painful in itself as I had to refactor the entirety of the cli. 😭

**Comment by bachig26** [comment]
> I'm not going to work on this but I'll accept a good pull request.
> 
> I think this problem can be solved if the cli options `-c` and `-ep` were used. The episode selector and watch options are just fallbacks to the command line. It's the command line that brings flexibility.
> 
> Implementing watch options was already quite painful in itself as I had to refactor the entirety of the cli. 😭

yes, i can see that. thank you so much. watch options is really nice and i really appreciate for it.
