### ISSUE TITLE
auto domain check while search incase of domain change

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#187]
**Describe the feature/change you'd like**

this request is for an ease of use incase of domain expired while searching a term and if the user forgot to do the update check before searching.

in my case, I do use the update checker `mov-cli --pupdate` weekly twice, but at times when searching some content, the domain may have changed, then I will run the above command.

**_but if there is a function that calls this update checker automatically when the domain expired or changed while searching a term will a nice touch that will reduce few steps and time correspondingly._**

**Expected behavior**

1. search a term (example: mission impossible) in a provider (example: sflix) => (example: https://sflix.se/search/mission-impossible)
2. if domain changed, the result will be empty (null)
3. in this case, the domain checker is called automatically (mov-cli --pupdate)
4. and if new domain exists then it'll be updated => (example: https://sflix.im)
5. after that it'll output the search result with the updated domain => (example: https://sflix.im/search/mission-impossible)

**Comment by ananasmoe** [comment]
V3 has been discontinued in favor of V4 and as this issue is related to V3 this issue will be closed.
