### ISSUE TITLE
Discussion about V4

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#188]
may I ask what can I expect on the public release of v4? features? improvements?
@THEGOLDENPRO @r3tr0ananas

**Comment by THEGOLDENPRO** [comment]
Honestly I don't know about what features we'll include apart from mov-cli also being a library that you can utilize in your projects but for improvements:

- cleaner codebase
- improved UI
- better expandability

**Comment by THEGOLDENPRO** [comment]
Feel free to mention features that you would like to see added in this issue.

**Comment by bachig26** [comment]
> Feel free to mention features that you would like to see added in this issue.

i thought of this feature idea for long time to have included, but not sure if it's possible.
**_which is an new version notification if a new version is available to update while launching `mov-cli`._**

**Comment by THEGOLDENPRO** [comment]
Yeah that would be possible, we could probably use the pypi API for that.

**Comment by bachig26** [comment]
> Feel free to mention features that you would like to see added in this issue.

2. possible addition of remembering search history along with the used provider.

**Comment by bachig26** [comment]
3. possibility to have custom font and color? @THEGOLDENPRO is this feasible with the current codebase? because i would like see something like this (https://github.com/IdreesInc/Monocraft) in mov-cli as a custom font.

ps. i know like I can change the font of the powershell or cmder in my case easily but i would like see an custom one just for mov-cli package, **_if any case i would to see more color options in cli_**.

**Comment by THEGOLDENPRO** [comment]
pinning this issue as I'm going to start bringing v4 development discussion here.

**Comment by bachig26** [comment]
@THEGOLDENPRO will every working sites from v3 will be available in the v4, right?

**Comment by THEGOLDENPRO** [comment]
> @THEGOLDENPRO will every working sites from v3 will be available in the v4, right?

Hopefully but I rather have fewer scrapers inturn of keeping them well-maintained and up-to-date, although feel free to add more scrapers at your will. I just would prefer whoever makes a scraper for a site should be responsible for keeping it maintained and up-to-date.

**Comment by bachig26** [comment]
add a `How To` section in Readme when v4 goes live, to give a basic info on how to add scrapers and such.
In my case, I'm not good at programming but still tried to learn how it works and what's need from v3 as most of them have same template for every sites, but when looked into the v4, it's completely different and I'm confused on where to begin with.

so it'll nice to have an little guide or such.

**Comment by THEGOLDENPRO** [comment]
> add a `How To` section in Readme when v4 goes live, to give a basic info on how to add scrapers and such.
> In my case, I'm not good at programming but still tried to learn how it works and what's need from v3 as most of them have same template for every sites, but when looked into the v4, it's completely different and I'm confused on where to begin with.
> 
> so it'll nice to have an little guide or such.

Yeah will do. V4 codebase is in its very early stages, I'm refactoring and changing it almost every day I touch it lmao, so as of right now the codebase is just a mock-up and **will** change.

I'm planning to perform a bunch of refactoring soon™ that should make scraper development easier and reduce overall source code.

**Comment by THEGOLDENPRO** [comment]
When I'm done with that and all is working I'll start development with the CLI interface then we can maybe get some documentation going.

**Comment by bachig26** [comment]
@r3tr0ananas @THEGOLDENPRO please have a look at this: https://github.com/charmbracelet/lipgloss

if this or similar terminal ui feature can be added for coloring and other similar ui stuff.

**Comment by THEGOLDENPRO** [comment]
> @r3tr0ananas @THEGOLDENPRO please have a look at this: https://github.com/charmbracelet/lipgloss
> 
> if this or similar terminal ui feature can be added for coloring and other similar ui stuff.

Oooh pretty cool, I'll keep it in mind in future UI updates.

**Comment by aditya-shri** [comment]
Will the "use as library" feature come in v4?

**Comment by THEGOLDENPRO** [comment]
> Will the "use as library" feature come in v4?

yes, it's being built from the ground up to "use as a library".

**Comment by THEGOLDENPRO** [comment]
For anyone who's desperate you can try out the new mov-cli (**V4**) from its branch: https://github.com/mov-cli/mov-cli/tree/v4

> [!NOTE]
> **However** do note. v4 is still in development so expect a lot of features to be missing and documentation to be lacking, and lastly expect many many bugs. 🐞

**Comment by THEGOLDENPRO** [comment]
Oh and if you plan on using it as a library expect breaking changes your way.

**Comment by THEGOLDENPRO** [comment]
For further discussion create an issue.
