### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by ashhad** [mov-cli/mov-cli#192]
**Describe the bug**
Unable to play any media from any provider. As soon as the title is selected an error is thrown saying:

AttributeError: 'NoneType' object has no attribute 'split'

**Expected behavior**
Video should play

**Screenshots**
Attached

**Desktop (please complete the following information):**
 -Androud 13 using Termux

**Additional context**

**Possible cause**
If you have a hunch on what might be causing this, please add it here.

**Possible solution**
If you know a way we could fix this, please add it here.

**Version**
Latest version installed using pip
![Screenshot_2023-09-14-00-58-27-52_84d3000e3f4017145260f7618db1d683](https://github.com/mov-cli/mov-cli/assets/7990188/b1692142-351c-4543-b269-ddef56c0e2cd)

**Comment by THEGOLDENPRO** [comment]
Do you have `fzf` installed? It's a required prerequisite.

**Comment by THEGOLDENPRO** [comment]
I think you should be able to install it with `sudo apt install fzf` on termux. Anyone correct me if I'm wrong.

> Do you have `fzf` installed? It's a required prerequisite.

**Comment by ashhad** [comment]
Hi goldy, it's already there.

fzf is already the newest version (0.42.0-1).

**Comment by ananasmoe** [comment]
V3 has been discontinued in favor of V4 and as this issue is related to V3 this issue will be closed.
