### ISSUE TITLE
Play on a different video player

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#195]
**Before asking**
Check through [Issues](https://github.com/mov-cli/mov-cli/issues) and closed ones too if your question was already answered.

**Question**
Enter your Question under here:

Is it possible to make mov-cli play the movie in to a video player of youre own choosing? If so, how?

Im on android and whant to make mov-cli play the movies i chose in to a vr video player

**Comment by ananasmoe** [comment]
It's only possible if you change the code for player selection yourself.

**Comment by THEGOLDENPRO** [comment]
yeah like ananas said this won't be possible in v3 without editing the source code. However, v4 will support custom players via a `config.toml` file so you might be able to pass something through the `player` key in v4 when it's released.

**Comment by THEGOLDENPRO** [comment]
Should have notified you earlier but I've added custom player support to v4 a while back. f207c09cb97eb9f56526fa6a75c65c2ac899fdba

It will be triggered if you pass an unrecognised player. It will use that player like so:
```sh
{player} {media_url}
```
This is what mov-cli v4 would do if for example MPV wasn't a recognised player and you set that as the `player` key in [config.toml](https://github.com/mov-cli/mov-cli/blob/v4/mov_cli/config.template.toml#L2):
```sh
mpv https://cdn.devgoldy.xyz/ricky.webm
```

**Comment by EbanNox** [comment]
Intresting, thank u for the anser! I will look forward to v4!!!

**Comment by THEGOLDENPRO** [comment]
https://github.com/mov-cli/mov-cli/issues/188#issuecomment-1981831492
