### ISSUE TITLE
[BUG] enimax-anime aka /blob/e4/key.txt gone

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#199]
enimax-anime key aka
https://github.com/enimax-anime/key/blob/e4/key.txt
Gone
The repositories whont even load on a browser... mov-cli now been cripled!

**Comment by EbanNox** [comment]
Same issue report here:
https://github.com/mov-cli/mov-cli/issues/200

**Comment by shinysocks** [comment]
same issue here...

**Comment by EbanNox** [comment]
@r3tr0ananas @Poseidon444 what is that key file for anyway, what is it and what is it used for? And is it possible not to use it?
Anything that can help me to contribute in this project and help maintain it 👍

**Comment by Poseidon444** [comment]
It was a file storing the decryption key for a site.

**Comment by EbanNox** [comment]
> It was a file storing the decryption key for a site.

I'm guessing the site using dokicloud?

**Comment by ananasmoe** [comment]
I am sorry for the long wait on the Update, Should be fixed now.

**Comment by ananasmoe** [comment]
Reopen if the issue still persists

**Comment by EbanNox** [comment]
> Reopen if the issue still persists

Yey, it works, great work @r3tr0ananas !!! Champ
