### ISSUE TITLE
Feature: Print year when Movie or Show was released

### ISSUE THREAD

**Issue by ttx99** [mov-cli/mov-cli#20]
for when the title is the same
![Screenshot_2022-07-02_14-34-20](https://user-images.githubusercontent.com/95531944/176989658-83e79dcf-a570-441c-9429-4e9a962a4107.png)

**Comment by git1230** [comment]
This definitely should be added, or at least considered.

**Comment by Poseidon444** [comment]
Will be done soon!

**Comment by ghost** [comment]
All Providers are now showing Release Date (excluding TheFlix)
