### ISSUE TITLE
Not working on Termux

### ISSUE THREAD

**Issue by Aridlvory** [mov-cli/mov-cli#200]
**Describe the bug**
First use and shows error in Termux

**Expected behavior**
Play movie

**Error**
![Screenshot_20231109-193652_Termux.jpg](https://github.com/mov-cli/mov-cli/assets/78092537/839af93e-d349-4da8-bf89-3ac963566d24)

**Desktop:**
 - OS: Linux (Termux)
 - Version: 0.5.3

**Comment by EbanNox** [comment]
Alredy mentioned here
https://github.com/mov-cli/mov-cli/issues/199
