### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VictorCunillera** [mov-cli/mov-cli#203]
**Describe the bug**
I installed mov-cli as the tutorial shows, and when I run it a number of errors pop up.

**Expected behavior**
To work when I write mov-cli.

**Error**
![image](https://github.com/mov-cli/mov-cli/assets/94693125/b1c2cb6a-b6c2-4666-88e8-c9b9d09ae2b8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Version**
Latest i guess, I didnt' got to choose what version to install.

**Comment by ananasmoe** [comment]
Please reinstall mov-cli again and try out again.

**Comment by ananasmoe** [comment]
Stale
