### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shinysocks** [mov-cli/mov-cli#204]
**Describe the bug**
Trying to stream any movie from solar or sflix results in a binascii Error.

**Expected behavior**
Search entry should play

**Error**
`binascii.Error: Invalid base64-encoded string: number of data characters (869) cannot be 1 more than a multiple of 4`

**Desktop (please complete the following information):**
 - OS: Pop OS

**Version**
- 1.5.6

**Comment by ananasmoe** [comment]
Fixed

**Comment by shinysocks** [comment]
Thank You!! Works great!
