### ISSUE TITLE
[BUG] android termux mpv activity start failiur

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#206]
**Describe the bug**
Trying to watch anything on any providers throws me back the same error where mov-cli can't start mpv app activity... wether using am command or not... testing with ani-cli does not exhibit this behaviur, and running a am command to start mpv also does not yield this error, only mov-cli yields this error

**Expected behavior**
Start mpv without a hitch on android where it streams the selected media to mpv

**Screenshots with error**
![Screenshot_20231209_221406_Termux.jpg](https://github.com/mov-cli/mov-cli/assets/108201516/4b475a18-b455-449a-93c2-b5fda4b1cf7d)

**Desktop (please complete the following information):**
 - OS: android 13 (ONE UI 5.1)
 - devise: Samsung Galaxy S21 Ultra 5G

**Possible cause**
My hypothesis is that mov-cli is beeing isolated by android system somehow preventing it to start any external app activity or mpv was auto updated on android where the method of starting it with passing argument has changed and mov-cli needs to accommodate for the change... not a expert tho, so I don't know

**Comment by EbanNox** [comment]
I have figured it out to some extent. Mpv was updated recently on my devise and they did change something to the [is.xyz.mpv.MPVActivity]...

As to my understanding is.xyz.mpv.MPVActivity is used to not only start mpv on android, but to allow to pass on a url or file in to the app while the is.xyz.mpv.MainActivity is just the main launcher for the app, not to pass any arguments... as it's methods are not implemented on it...

Testing to launch mpv latest installed version on my android (2023-11-30-release) (latest on Google play and f-droid) 
Yields the same result... I am unable to launch nor use the is.xyz.mpv.MPVActivity in any way, as it seem to have been changed in this version... but downgrading too 2023-08-27-release resolves the problem and the is.xyz.mpv.MPVActivity works as intended....

Those who updated mpv recently and have this issue, id resolve it temporarily by manualy downgrading to the previus version of mpv witch can be easily accomplished by visiting "f-droid"

I'm resolving this issue by downgrading mpv....

But it still does not anser how ani-cli was able to launch mpv without updating it... it might have some ingenious method of launching apps on android,  id look in to it...

While at it, why not add the feature that allows u to instantly play a movie or a episode if the entire (-s "search query") instantly finds or matches to what the query is, and auto selects it and forwards the action to instantly scrape them start mpv, like ani-cli does.... it u type in ani-cli 
(Ani-cli --dub -r "1-100" "overlord III") will result in instantly playing the episode of the  queried series, as it instantly matches the name and findes no extra options but one in the result from query, initializing the automated action to instantly start an episode from it.. without having to still selecting what returns from the search result query in fzf etc.

**Comment by Poseidon444** [comment]
I'll try looking into it

**Comment by ananasmoe** [comment]
V3 has been discontinued in favor of V4 and as this issue is related to V3 this issue will be closed.
