### ISSUE TITLE
[BUG] --pupdate did not work to accommodate some of the Domaine name changes of cuple providers

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#207]
Mov-cli was unable to update provider link names. Like sflix.se is now sflix.to, --pupdate was not able to update

**Comment by bachig26** [comment]
> Mov-cli was unable to update provider link names. Like sflix.se is now sflix.to, --pupdate was not able to update 

sflix.se was a clone of sflix.to and always been maintained by a different maintainer i guess.

furthermore, sflix.se in browser and with mov-cli still works for me, maybe some issue with slow server at the moment or your isp issue. check it first.

**Comment by EbanNox** [comment]
> > Mov-cli was unable to update provider link names. Like sflix.se is now sflix.to, --pupdate was not able to update 
> 
> sflix.se was a clone of sflix.to and always been maintained by a different maintainer i guess.
> 
> furthermore, sflix.se in browser and with mov-cli still works for me, maybe some issue with slow server at the moment or your isp issue. check it first.

Will do today, hold on for my reply

**Comment by EbanNox** [comment]
> > Mov-cli was unable to update provider link names. Like sflix.se is now sflix.to, --pupdate was not able to update 
> 
> sflix.se was a clone of sflix.to and always been maintained by a different maintainer i guess.
> 
> furthermore, sflix.se in browser and with mov-cli still works for me, maybe some issue with slow server at the moment or your isp issue. check it first.

Sflix now works egain, so it was propably a local issue
