### ISSUE TITLE
[QUESTION] How to stream in lower qualiy?

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#208]
**Question**
What argument do I pass after mov-cli to makenit fetch the stream i select in loger quality such like 720p?

**Comment by bachig26** [comment]
> **Question** What argument do I pass after mov-cli to makenit fetch the stream i select in loger quality such like 720p?

right now, there is no option to select the quality in mov-cli.

**Comment by ananasmoe** [comment]
@THEGOLDENPRO, I have found a solution for mpv: `--hls-bitrate=resolution`, but I didn't really find something for VLC.

**Comment by THEGOLDENPRO** [comment]
> @THEGOLDENPRO, I have found a solution for mpv: `--hls-bitrate=resolution`, but I didn't really find something for VLC.

Yeah that would be perfect for mpv. https://man.archlinux.org/man/mpv.1#hls

**Comment by ananasmoe** [comment]
https://github.com/mov-cli/mov-cli/commit/5f7cb58d9f20d0c505bb5390477b940bfc98a955
