### ISSUE TITLE
[Provider] thetvapp.to

### ISSUE THREAD

**Issue by ttx99** [mov-cli/mov-cli#209]
**Website**
https://thetvapp.to/
Website:  https://thetvapp.to/

**Extras**
Basically USTVGO replacement without the need for VPN and has more channels and super stable streams.
This provider also has sports.

**Comment by THEGOLDENPRO** [comment]
The scrapers in v4 should be quite good. I would recommend you give it a try. 
Also usually changing your DNS will allow you to access sites if they are blocked, there's no need for a VPN from my understanding.

**Comment by THEGOLDENPRO** [comment]
Closing this as it's related to V3.
