### ISSUE TITLE
[FEATURE] Please add syncplay support 

### ISSUE THREAD

**Issue by jrosenholtz** [mov-cli/mov-cli#212]
**Describe the feature/change you'd like**
Launch and add video to syncplay using a commandline arg, similar to ani-cli

**Comment by 4cecoder** [comment]
Hi there,

I'm the new active maintainer of this project.

please link syncplay and other stuff to do with that here so I can look into adding support

@jrosenholtz

**Comment by jrosenholtz** [comment]
Here is the syncplay github: https://github.com/Syncplay/syncplay
Here is the ani-cli github: https://github.com/pystardust/ani-cli

ani-cli uses command line arg -s to automatically pull the file into syncplay. Thank you for responding to my feature request

**Comment by ananasmoe** [comment]
This is would be achievable using the player configuration. Please refer to the wiki, link: https://github.com/mov-cli/mov-cli/wiki/Configuration#player
