### ISSUE TITLE
[BUG] sports provider scdn sports genre selection not working.

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#214]
**Describe the bug**
after selecting scdn u r provided with different sports option within scdn, and all of them are broken

**Expected behavior**
to continue to select from the sport selection menu and forward to watch the sport

**Screenshots**
![ScreenShot_20240110133015](https://github.com/mov-cli/mov-cli/assets/108201516/132ea806-4a2c-4618-b5a1-412e03e85cdd)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version: 22H2

**Additional context**

**Possible cause**
If you have a hunch on what might be causing this, please add it here.

**Possible solution**
If you know a way we could fix this, please add it here.

**Version**
mov-cli v1.5.7

**Comment by EbanNox** [comment]
its the same result on my frends windows 10 pc

**Comment by ananasmoe** [comment]
V3 has been discontinued in favor of V4 and as this issue is related to V3 this issue will be closed.
