### ISSUE TITLE
[BUG] Incorrect padding

### ISSUE THREAD

**Issue by SellBound** [mov-cli/mov-cli#218]
**Describe the bug**
Everything is working untill it is trying to start the payer and the same error as #213 and #158 pops up

**Expected behavior**
mpv is expected to start playing selected content

**Screenshots**
![Screenshot_20240120_145701_com.termux.jpg](https://github.com/mov-cli/mov-cli/assets/107553530/868c93c7-a983-46c2-b012-b32abf3f5096)

**Desktop (please complete the following information):**
 - OS: Android
 - Version: 12

**Version**
mov-cli 1.5.7
pip 23.3.2
mpv-android 2023-11-30-release
lxml 5.1.0
ffmpeg 6.1

**Update**
I did not do anything to fix this, but now it is working just fine, still do not know the reason the error occured.

**Comment by EbanNox** [comment]
I'm posting a question about this and it's related problems we are all experiencing with v3 here -> https://github.com/mov-cli/mov-cli/issues/231

**Comment by Poseidon444** [comment]
Yea, decryption has broken down

**Comment by ananasmoe** [comment]
V3 has been discontinued in favor of V4 and as this issue is related to V3 this issue will be closed.
