### ISSUE TITLE
[BUG] VLC not working due to wrong arg --no-terminal

### ISSUE THREAD

**Issue by GreatTeacherOni** [mov-cli/mov-cli#219]
**Describe the bug**
When running `mov-cli --vlc` and the video is trying to open it takes a second and then shows the menu again. After quitting mov-cli, the terminal shows following error:
``vlc: unknown option or missing mandatory argument `--no-terminal'``
``Try `vlc --help' for more information.``

**Expected behavior**
mov-cli --vlc opens VLC player

**Screenshots**
![Screenshot_mov-cli_vlc_error](https://github.com/mov-cli/mov-cli/assets/8284970/0c7b1ecd-2a9a-4e73-b9db-66f3790f05fa)

**Error**
See screenshot

**Desktop (please complete the following information):**
 - OS: NixOS / Ubuntu 20.04 (WSL)
 
**Additional Context**
mov-cli is installed via `pip install mov-cli`(Python 3.11.7)

**Possible cause**
As the error message suggests, there is no argument `--no-terminal` for `vlc`

**Possible solution**
When line 65 in players.py is commented out (which removes --no-terminal as an arg that is handed over) it opens VLC player

**Version**
1.5.7

**Comment by THEGOLDENPRO** [comment]
fixed in v4
