### ISSUE TITLE
[BUG] VLC player opens with error message

### ISSUE THREAD

**Issue by GreatTeacherOni** [mov-cli/mov-cli#220]
**Describe the bug**
Running `mov-cli --vlc` opens the VLC player after choosing an episode of a series but a popup error message appears

**Expected behavior**
VLC should open and play the chosen content

**Screenshots**
![Screenshot_mov-cli_vlc_error_popup](https://github.com/mov-cli/mov-cli/assets/8284970/1979fa7e-13da-48b7-abac-09e9c74bd2c8)

**Error**
VLC is unable to open the MRL '"https://oi321o.video-delivery.net/u5kj756hmxdlsdgge56q2ocoilalmxaczqh6b62bxi6w67qqiwd2gjofj5xa/tf4qu79h10~MovCli3oPi?token=p4gzhyiioy4qmb50q7qwjfh8"'. Check the log for details.

vlc.log (debug mode) shows following error (snippet out of the whole log):

> ...
> main debug: using default timeshift path
>  221   ``│ main debug: `"https://oi321o.video-delivery.net/u5kj756hmxdlsdgge56q2ocoilalmxaczqh6b62bxi6w67qqiwd2gjofj5xa/tf4qu79h10~MovCli3oPi?token=p4gzhyiioy4qmb50q7qwjfh8"' gives access `"https' demux `any' pat``
>        ``│ h `oi321o.video-delivery.net/u5kj756hmxdlsdgge56q2ocoilalmxaczqh6b62bxi6w67qqiwd2gjofj5xa/tf4qu79h10~MovCli3oPi?token=p4gzhyiioy4qmb50q7qwjfh8"'``
>  222   ``│ main debug: creating demux: access='"https' demux='any' location='oi321o.video-delivery.net/u5kj756hmxdlsdgge56q2ocoilalmxaczqh6b62bxi6w67qqiwd2gjofj5xa/tf4qu79h10~MovCli3oPi?token=p4gzhyiioy4qmb50q7qwjfh8"' file='(null)'``
>  223   │ main debug: looking for access_demux module matching ""https": 17 candidates
>  224   │ main debug: no access_demux modules matched
>  225   │ main debug: creating access: "https://oi321o.video-delivery.net/u5kj756hmxdlsdgge56q2ocoilalmxaczqh6b62bxi6w67qqiwd2gjofj5xa/tf4qu79h10~MovCli3oPi?token=p4gzhyiioy4qmb50q7qwjfh8"
>  226   │ main debug: looking for access module matching ""https": 27 candidates
>  227   │ main debug: no access modules matched
>  228   │ main debug: looking for meta fetcher module matching "any": 1 candidates
>  229   │ lua debug: Trying Lua scripts in /home/<user>/.local/share/vlc/lua/meta/fetcher
>  230   │ lua debug: Trying Lua scripts in /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/fetcher
>  231   │ lua debug: Trying Lua scripts in /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/share/vlc/lua/meta/fetcher
>  232   │ main debug: no meta fetcher modules matched
>  233   │ main debug: looking for art finder module matching "any": 2 candidates
>  234   │ main debug: dead input
>  235   │ main debug: changing item without a request (current 0/1)
>  236   │ main debug: nothing to play
>  237   │ lua debug: Trying Lua scripts in /home/<user>/.local/share/vlc/lua/meta/art
>  238   │ lua debug: Trying Lua scripts in /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art
>  239   │ lua debug: Trying Lua playlist script /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art/00_musicbrainz.luac
>  240   │ lua debug: skipping script (unmatched scope) /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art/00_musicbrainz.luac
>  241   │ lua debug: Trying Lua playlist script /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art/01_googleimage.luac
>  242   │ lua debug: skipping script (unmatched scope) /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art/01_googleimage.luac
>  243   │ lua debug: Trying Lua playlist script /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art/02_frenchtv.luac
>  244   │ lua debug: skipping script (unmatched scope) /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art/02_frenchtv.luac
>  245   │ lua debug: Trying Lua playlist script /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art/03_lastfm.luac
>  246   │ lua debug: skipping script (unmatched scope) /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/lib/vlc/lua/meta/art/03_lastfm.luac
>  247   │ lua debug: Trying Lua scripts in /nix/store/id6hzv0jha9z0zhmj9lqj7nrqhg1dp97-vlc-3.0.20/share/vlc/lua/meta/art
>  248   │ main debug: no art finder modules matched
>  249   │ qt debug: video widget is orphaned
>  250   │ main debug: exiting
>  251   │ main debug: exiting
>  ...
> 

**Desktop (please complete the following information):**
 - OS: NixOS

**Additional context**

**Possible cause**
Unknown but maybe the link that is given to vlc is (partly) wrong.

**Possible solution**
If the link is (partly) wrong the part that builds or hands it over should be fixed.

**Version**
1.5.7

**Comment by THEGOLDENPRO** [comment]
I've done some fixes to the vlc player in mov-cli v4 so I recommend you try it out: https://github.com/mov-cli/mov-cli/issues/188#issuecomment-1981831492

**Comment by ananasmoe** [comment]
V3 has been discontinued in favor of V4 and as this issue is related to V3 this issue will be closed.
