### ISSUE TITLE
[QUESTION] Is v3 maintained anymore? Or we wait for v4?

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#231]
I wanted to touch base regarding the current status of v3. It seems like there's been a bit of a hiccup lately with the maintenance and functionality. It's been quite some time since v3 has been working smoothly for anyone. I've personally been eagerly awaiting an update for over a month now, especially since the encryption key seems to be causing issues and hasn't been maintained.

I'm finding it impossible to stream anything using mov-cli anymore; every provider I try gives me padding errors and other issues. 

So, I was wondering, are we still waiting on a fix for v3? Or perhaps considering moving on to v4 instead?

What's the uppdate? ^^

**Comment by Poseidon444** [comment]
The current plan is to maintain v3 until v4 is ready,i understand how frustrating this has been. I will focus on fixing it today.
Thank you.

**Comment by EbanNox** [comment]
> The current plan is to maintain v3 until v4 is ready,i understand how frustrating this has been. I will focus on fixing it today.
> Thank you.

I apologize if I seemed frustrated earlier, but honestly, I'm feeling quite motivated. I really want to lend a hand and help ease the workload.

I'd love to be part of the maintenance team. The thing is, I'm not too familiar with the code base and its structure. While I know some Python, I'm not yet adept at creating advanced structures and statements right off the bat.
However, I believe with some guidance, I could eventually become proficient and assist in maintaining the project from version 3 onwards to version 4.

If you're unsure about which component I could handle, perhaps you could teach me about encryption/decryption keys and their system or setup. I could then be on standby to maintain them if they malfunction or if there are issues with padding.

Teach me the ins and outs, and I'll be ready to jump in whenever maintenance is needed.

I currently have a lot of free time, and I'd be more than happy to help out.

**Comment by ananasmoe** [comment]
> If you're unsure about which component I could handle, perhaps you could teach me about encryption/decryption keys and their system or setup. I could then be on standby to maintain them if they malfunction or if there are issues with padding.

Well the decryption keys are just a hit or miss. I kinda got it to work but i still don't know anything about the decryption. >:(

**Comment by THEGOLDENPRO** [comment]
If you're desperate: https://github.com/mov-cli/mov-cli/issues/188#issuecomment-1981831492

**Comment by THEGOLDENPRO** [comment]
v3 is no longer being maintained. If you want *something* I would recommend trying out v4's development build as that is in a better state. Closing this now.
