### ISSUE TITLE
Providers

### ISSUE THREAD

**Issue by Poseidon444** [mov-cli/mov-cli#232]
Can I please know the providers that you guys frequently use ?( So that I can maintain them)

**Comment by ttx99** [comment]
fix movies and sports

**Comment by R41DAJ** [comment]
Hi Poseidon444, I usually use  sflix and solar, Thanks for everything

**Comment by EbanNox** [comment]
English providers: Remote stream, sflix
And the Sports providers

**Comment by shinysocks** [comment]
> Hi Poseidon444, I usually use sflix and solar, Thanks for everything

^ + remotestream

**Comment by ananasmoe** [comment]
> ^ + remotestream

RemoteStream doesn't exist anymore.

**Comment by shinysocks** [comment]
aw dang

**Comment by shinysocks** [comment]
I don't know what the source is but supernova.to is pretty great

**Comment by ananasmoe** [comment]
If you want to recommend a website please to it at: [mov-cli-films](https://github.com/mov-cli/mov-cli-films) for film sites and [mov-cli-anime](https://github.com/mov-cli/mov-cli-anime) for anime sites

**Comment by shinysocks** [comment]
done.
