### ISSUE TITLE
[Plugin Request] NBA

### ISSUE THREAD

**Issue by ttx99** [mov-cli/mov-cli#239]
https://topstreams.info/nba/bucks
or

[https://topstreams.info/nba/{Team](https://topstreams.info/nba/%7BTeam) Name without Location}
so if the schedule is Bulls @ Bucks (home team)
the link is https://topstreams.info/nba/bucks or https://topstreams.info/nba/bulls
this is the official NBA league pass stream bro I hope you consider

**Comment by ananasmoe** [comment]
We don't know if we'll add it.

**Comment by ttx99** [comment]
but will you guys bring sports back?

**Comment by ananasmoe** [comment]
We don't know. But as v4 now supports plugins that means somebody can do it, if we don't.

**Comment by ananasmoe** [comment]
I looked at topstreams and it had some issue but i forgot what it was, so this can't be added.

**Comment by ttx99** [comment]
How about this https://the.streameast.app/ this covers most sports and its stable.

**Comment by ananasmoe** [comment]
This also won't work. The original site operates like this: they retrieve the media every 5 seconds because they are only providing a 5-second clip and in mov-cli this would be kinda hard to add.

**Comment by ttx99** [comment]
thetvapp.to

**Comment by THEGOLDENPRO** [comment]
I don't think we'll be maintaining such websites. If someone wants this added they are free to create a plugin so I'll be closing this as unplanned.
