### ISSUE TITLE
[FEATURE] Binge Mode

### ISSUE THREAD

**Issue by ugaugabuga** [mov-cli/mov-cli#240]
When watching a series or anime mov-cli closes entirely after each episode and you'll have to start the entire procedure from the beginning to watch the next episode. A binge mode like anipy-cli would be great. If you're not interested in that you can make the script to not exit after playback finishes and let it stay on episode selection menu.

**Comment by THEGOLDENPRO** [comment]
yeah, this will be implemented. #226 is the issue you should track. 👍

**Comment by ugaugabuga** [comment]
Thanks! I'm gonna close this as it's a duplicate issue.
