### ISSUE TITLE
[OFF-TOPIC] I'll be absent from Discord.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli#241]
@r3tr0ananas I should have given a heads-up much earlier but I will be absent from Discord for a month so if anyone tries to interact with me let them know that.

And to everyone else if there are any issues reported or features thought of on the Discord that I should overlook, forward them to the respective github repo, thanks. That's where I will be able to communicate and help. 😊

**Comment by r3tr0ananas** [comment]
@THEGOLDENPRO quick question, i am currently making my website and to create linkers which you have, so could i use your code and mention you?

**Comment by ananasmoe** [comment]
> I will be absent from Discord for a month.

Is there a another way to chat so via mail or something?

**Comment by THEGOLDENPRO** [comment]
> > I will be absent from Discord for a month.
> 
> Is there a another way to chat so via mail or something?

What's your email?

**Comment by r3tr0ananas** [comment]
I hope you don't use Outlook as they block my mails. 💀

**Comment by r3tr0ananas** [comment]
mail at this address and i'll respond with a different mail address as the r3tr0ananas.pro mails use cloudflare's email-routing
