### ISSUE TITLE
[FEATURE] Publish v4 to pypi.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli#242]
The landscape has changed, v3 is no longer being maintained and v4 has become the default branch. 

v3 doesn't work function at all and v4 (the core mov-cli package) is becoming more stable, I think this calls to start publishing v4 as a package on pypi. 

Also @r3tr0ananas can you add me as maintainer for the mov-cli pypi package.

**Comment by ananasmoe** [comment]
> Also @r3tr0ananas can you add me as maintainer for the mov-cli pypi package.

![image](https://github.com/mov-cli/mov-cli/assets/132799819/e9a2a284-e172-4384-ad5f-bd8f0d705149)

**Comment by THEGOLDENPRO** [comment]
ah it's @Poseidon444 that has to add me then. ^

**Comment by ananasmoe** [comment]
@THEGOLDENPRO you have to make the mov-cli-test a pypi package as i can't upload it.

```Invalid value for requires_dist. Error: Can't have direct dependency: 'mov-cli-test @ git+https://github.com/THEGOLDENPRO/mov-cli-test'```

**Comment by THEGOLDENPRO** [comment]
alright I'll publish it to pypi

**Comment by THEGOLDENPRO** [comment]
done: https://pypi.org/project/mov-cli-test/

**Comment by ananasmoe** [comment]
mov-cli v4 is now on pypi: https://pypi.org/project/mov-cli/4.0.0a2/

**Comment by THEGOLDENPRO** [comment]
Actually maybe I should have not made it an alpha version. I think we should change the version to 4.0.0 then release that.

**Comment by ananasmoe** [comment]
Alright, i changed the version to 4.0.0: https://pypi.org/project/mov-cli/4.0.0/

**Comment by THEGOLDENPRO** [comment]
Thanks 👍

**Comment by ananasmoe** [comment]
@THEGOLDENPRO I have send you an invitation to the mov-cli PyPi Project

**Comment by THEGOLDENPRO** [comment]
> @THEGOLDENPRO I have send you an invitation to the mov-cli PyPi Project

accepted thanks 👍
