### ISSUE TITLE
[FEATURE] Documentation for Android install

### ISSUE THREAD

**Issue by AbdoMoh96** [mov-cli/mov-cli#246]
the readme file should contain Documentation for android, thanks.

**Comment by THEGOLDENPRO** [comment]
I can add that to the wiki. What steps would you like to be documented exactly?

**Comment by EbanNox** [comment]
I can work on this, send me all that is needed, I'll start with it right now

**Comment by EbanNox** [comment]
> the readme file should contain Documentation for android, thanks.
> 

> I can add that to the wiki. What steps would you like to be documented exactly?

I can work on this, send me all that is needed, I'll start with it right now

**Comment by THEGOLDENPRO** [comment]
Alright feel free to write up documentation for Android, particularly installation instructions for Termux and I'll add it to the wiki whenever you're done. (or I guess make a pr if you can, _I have no idea how wiki works on GitHub_ 😅)

**Comment by ananasmoe** [comment]
https://github.com/mov-cli/mov-cli/wiki/Installation:-iOS-&-Android

I would add documentation for android but i ~luckily~ sadly do not own a android device.

**Comment by EbanNox** [comment]
> https://github.com/mov-cli/mov-cli/wiki/Installation:-iOS-&-Android
> 
> I would add documentation for android but i ~luckily~ sadly do not own a android device.

I'm almost done with everything so don't worry, gotcha covered

**Comment by AbdoMoh96** [comment]
I already managed to install it on my Android phone and Android TV works fine I had a small bug but @THEGOLDENPRO helped me with it i can write a full Android installation documentation and make a PR for it, unless @EbanNox already finished writing it.

**Comment by THEGOLDENPRO** [comment]
> I already managed to install it on my Android phone and Android TV works fine I had a small bug but @THEGOLDENPRO helped me with it i can write a full Android installation documentation and make a PR for it, unless @EbanNox already finished writing it.

Android TV is crazy, I didn't really think of that. 😂

Could you actually use your remote to select stuff from the fzf prompt menu?

**Comment by AbdoMoh96** [comment]
yes I can, but using keyboard is much better I have a wireless keyboard and mouse makes using terminal much easier.

**Comment by AbdoMoh96** [comment]
I use "Xiaomi TV Box S (2nd Gen)" you can send APK files to the TV using an app called "Send Files To TV" send the Termux apk and install it then install python and the rest is exactly like any android phone.

**Comment by THEGOLDENPRO** [comment]
fu#king amazing, glad to hear. 😂

**Comment by ananasmoe** [comment]
> I use "Xiaomi TV Box S (2nd Gen)" you can send APK files to the TV using an app called "Send Files To TV" send the Termux apk and install it then install python and the rest is exactly like any android phone.

I am currently installing mov-cli on my FireTV and i don't have a wireless keyboard and either have to use my phone or adb which both are a pain.

**Comment by THEGOLDENPRO** [comment]
I'm going to add vlc support for android as it has really good casting support for Google devices and TVs. *Totally not trying to convert my parents to using the command line or anything.*

**Comment by ananasmoe** [comment]
omg, i got ssh server installed only took ages with adb. 💀

**Comment by THEGOLDENPRO** [comment]
> I'm going to add vlc support for android as it has really good casting support for Google devices and TVs. *Totally not trying to convert my parents to using the command line or anything.*

and done, it works first try too 😎

**Comment by ananasmoe** [comment]
BTW i added Instructions on how to install it on termux: https://github.com/mov-cli/mov-cli/wiki/Installation#android-via-termux-

Could anyone test it?

**Comment by THEGOLDENPRO** [comment]
what is `rei` and `libexpat`?

**Comment by ananasmoe** [comment]
I think `rei` is just a abbreviation for reinstall and i don't really what `libexpat` that but i had to install it to use pypi

**Comment by THEGOLDENPRO** [comment]
> I think `rei` is just a abbreviation for reinstall and i don't really what `libexpat` that but i had to install it to use pypi

Weird, usually you just install python and python-pip.

**Comment by ananasmoe** [comment]
> Weird, usually you just install python and python-pip.

I only installed python while installing it did print something with setting pip up or something so didn't think of installing python-pip.

**Comment by THEGOLDENPRO** [comment]
I would try and confirm this all if Termux's GOD DAMN DOCKER CONTAINER WORKED ALREADY!

![image](https://gifdb.com/images/high/angry-anime-taiga-aisaka-opwaxen9aznbc18j.gif)

**Comment by THEGOLDENPRO** [comment]
If I can get my second android phone up and running I'll be able to create a good step by step installation guide.

**Comment by THEGOLDENPRO** [comment]
I updated the Android install instructions: https://github.com/mov-cli/mov-cli/wiki/Installation#-android-via-termux

This now should be correct, I tested it on a fresh device. Let me know if there's something wrong, closing the issue for now as completed.

**Comment by Jagadishwar49** [comment]
> I updated the Android install instructions: https://github.com/mov-cli/mov-cli/wiki/Installation#-android-via-termux
> 
> This now should be correct, I tested it on a fresh device. Let me know if there's something wrong, closing the issue for now as completed.

Can add that new version of mpv is not working on Android

**Comment by THEGOLDENPRO** [comment]
> > I updated the Android install instructions: https://github.com/mov-cli/mov-cli/wiki/Installation#-android-via-termux
> > 
> > This now should be correct, I tested it on a fresh device. Let me know if there's something wrong, closing the issue for now as completed.
> 
> Can add that new version of mpv is not working on Android 
> 

That's odd, the latest version (2023-11-30) has always worked for me. It would be appreciated if you could open an issue for this. 👍
