### ISSUE TITLE
[BUG] got FileNotFoundError when running "mov-cli -e"

### ISSUE THREAD

**Issue by AbdoMoh96** [mov-cli/mov-cli#248]
**Describe the bug:**
got a missing file or directory error

**Expected behavior:**
1- install python3 on android using termux
2- run :: pkg install python3
3- run :: mov-cli mov-cli -e
should be able to edit mov-cli config but got error instead

**Screenshots**
![WhatsApp Image 2024-03-14 at 23 22 03_add681c6](https://github.com/mov-cli/mov-cli/assets/46398025/24900a2b-16c6-4352-a874-0d606fbd383e)

**Error:**
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/.config/mov-cli'

**Platform (please complete the following information):**
 - OS: [e.g.android]
 - Version: [e.g. 0.5.8]

**Comment by THEGOLDENPRO** [comment]
Can you confirm if the error persists after creating ``.config``:
```sh
mkdir /data/data/com.termux/files/home/.config
```

If this fixes it then I know the issue exactly and I'll patch it very soon.

**Comment by AbdoMoh96** [comment]
turns out i just needed to create .config directory this command fixed my issue
`mkdir -p /data/data/com.termux/files/home/.config/mov-cli`
thanks @THEGOLDENPRO you are a hero

**Comment by THEGOLDENPRO** [comment]
Nice. However this is going to be an issue for new users so I'll patch mov-cli soon to create that directory if it doesn't exist.

**Comment by AbdoMoh96** [comment]
awesome work, keep it going.
