### ISSUE TITLE
[BUG] unable to edit config on ish

### ISSUE THREAD

**Issue by ashhad** [mov-cli/mov-cli#250]
**Describe the bug:**
Unable to edit the configuration file using ish on iOS. 
FileNotFoundError: No such file or directory /root/Library/mov-cli

**Expected behavior:**
Config file should be editable 

**Screenshots**

**Error:**
* Show full terminal output.
* Make sure to run mov-cli with ``--debug`` flag for full output.

```python
{terminal_output}
```

**Platform (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 0.5.8]

**Additional context / possible cause or solution:**
Add any other context about the problem here or possible causes and solutions.

**Version**
If you don't use the latest Version and create a Bug-Report, it will be closed and left unanswered.

**Comment by ananasmoe** [comment]
We know that there some issues with mov-cli and iOS.

**Comment by THEGOLDENPRO** [comment]
I think that "Library" directory has to be created, I patched a very similar bug with Andriod today. #248

Here was my fix, I think the same should be duplicated for iOS: https://github.com/mov-cli/mov-cli/commit/27704d7e59eb76e5e24cb4f40af30c16e4075401

**Comment by ananasmoe** [comment]
This issue is now fixed with the newest version.

See: https://github.com/mov-cli/mov-cli/commit/519b6b4b0dc0ee610a4923cf382ffd1204ae95fa
