### ISSUE TITLE
[BUG] Hyperlink problem with URLs that contain semicolons.

### ISSUE THREAD

**Issue by ananasmoe** [mov-cli/mov-cli#251]
@THEGOLDENPRO 

vidsrc.to provides a URL with a semicolon; without it, the hyperlink won't be clickable. 

I tried to escape it with a backslash, but had no luck. 

Without the semicolon, the hyperlink is clickable but doesn't function properly. 

Do you have any ideas on how to fix this? 

Alternatively, we could display the URL for the user to copy and paste into their browser.

**Comment by THEGOLDENPRO** [comment]
I think you have to encode that URL using ``quote()`` from ``urllib.parse``. Try that.

**Comment by ananasmoe** [comment]
I just tried, but this also does not work.

**Comment by THEGOLDENPRO** [comment]
ummm 🤔

I was gonna say "can iSH be emulatored on a desktop or something as ~~luckily~~ sadly I don't own an iPhone to debug this closer" but then I realised that wouldn't really help me debug it anyways.

**Comment by ananasmoe** [comment]
I also tried using the webbrowser module, but it doesn't do anything in iSH.

**Comment by THEGOLDENPRO** [comment]
I'm gonna go see if ani-cli does it any different.

**Comment by ananasmoe** [comment]
btw you can also emulate iSH by just using a alpine linux docker container.

**Comment by THEGOLDENPRO** [comment]
> btw you can also emulate iSH by just using a alpine linux docker container.

ah okay

**Comment by THEGOLDENPRO** [comment]
Ah I think they do it the same way: 
https://github.com/pystardust/ani-cli/blob/0bf639c4232538f9cca38571791ac5ccc9eae858/ani-cli#L259-L263

**Comment by ananasmoe** [comment]
we can paste the link directly into the clipboard and then let the user paste it into their browser; This would be a solution to this problem

**Comment by ananasmoe** [comment]
https://github.com/mov-cli/mov-cli/commit/5bac90ef949b76d47717982f12a817363b62dcec
