### ISSUE TITLE
[BUG] time out error on Android 

### ISSUE THREAD

**Issue by ashhad** [mov-cli/mov-cli#252]
**Describe the bug:**
App was working fine yesterday butnhas been giving connection time out error

**Expected behavior:**
Application should work properly

**Screenshots*

**Error:**

File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out

**Platform (please complete the following information):**
 Android
Mov-cli ![Screenshot_20240316-220646.png](https://github.com/mov-cli/mov-cli/assets/7990188/fc2a7b6e-6b8d-4740-99e7-fd1ba4dd638a)

Version: 4.0.5

**Additional context / possible cause or solution:**
Add any other context about the problem here or possible causes and solutions.

**Version**
If you don't use the latest Version and create a Bug-Report, it will be closed and left unanswered.

**Comment by THEGOLDENPRO** [comment]
Can you run mov-cli with the ``--debug`` command line option then copy and paste the full output you get here.

**Comment by ashhad** [comment]
It seems fixed now. May be a network issue at my end.

**Comment by EbanNox** [comment]
> It seems fixed now. May be a network issue at my end.

Was about to say that. it's a network issue

**Comment by THEGOLDENPRO** [comment]
> It seems fixed now. May be a network issue at my end.

Yeah maybe, thanks for the confirmation.
