### ISSUE TITLE
add option to upgrade injected package to wiki

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#254]
I would like to point out that it would be helpful to add this command line who are new in using the injected packages and upgrading them in future.

`pipx upgrade <package> --include-injected`

**Comment by THEGOLDENPRO** [comment]
I'm actually new to pipx myself 😊, would `mov-cli` go in `<package>` here?

**Comment by bachig26** [comment]
> I'm actually new to pipx myself 😊, would `mov-cli` go in `<package>` here?

yes

**Comment by THEGOLDENPRO** [comment]
thanks so much, I'll add that

**Comment by THEGOLDENPRO** [comment]
Done
