### ISSUE TITLE
[BUG] installing mov-cli on iOS with pipx doesn't work

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#256]
**Describe the bug:**
can't able to run the program.
i did install using pipx and injected the plugins.
i have also checked the injected packages by listing them and tried again as fresh install but still doesn't run.

**Expected behavior:**
to run.

**Screenshots**

![IMG_0950](https://github.com/mov-cli/mov-cli/assets/96393348/c972768f-fc3e-465a-8004-140bf70f24d6)

**Error:**
I got the same output even with debug flag as above screenshot.

**Platform (please complete the following information):**
 - OS: iOS
 - Version: 17.4

**Version**
mov-cli 4.0.7 (latest)

**Comment by ananasmoe** [comment]
I tried to install pipx on my phone, but it wouldn't install. However, for iSH, I used normal pip.

**Comment by bachig26** [comment]
> I tried to install pipx on my phone, but it wouldn't install. However, for iSH, I used normal pip.

maybe because I use the latest Alphine version (v3.19) in iSH, which shows the PEP 668 error. so, i can only install mov-cli using pipx.

**Comment by ananasmoe** [comment]
Firstly, how did you update your Alpine version and secondly iSH installs with version 3.14.3.

**Comment by bachig26** [comment]
> Firstly, how did you update your Alpine version and secondly iSH installs with version 3.14.3.

i run the ish from testflight which has the daily builds [v1.3.3 Build 617]. and it has the version 3.19 which came yesterday.

**Comment by ananasmoe** [comment]
![image](https://github.com/mov-cli/mov-cli/assets/132799819/dfdff566-b9b1-40ae-8a64-6be8ee590850)

Yeah i think I won't be able test it.

**Comment by r3tr0ananas** [comment]
Goddamn that screenshot is long

**Comment by bachig26** [comment]
> Goddamn that screenshot is long

yeah :)
oh, wasn't aware that it's full. maybe i'll try the app store version later today.

**Comment by ananasmoe** [comment]
> > Goddamn that screenshot is long
> 
> yeah :) oh, wasn't aware that it's full. maybe i'll try the app store version later today.

I will test it once it isn't full anymore.

**Comment by THEGOLDENPRO** [comment]
I didn't think they would be disabling pip too. Also btw there is a flag you can set to force your system wide pip to install mov-cli (I don't remember it rn) but I wouldn't recommend this on an actual Linux desktop as you simply have more to lose.

@r3tr0ananas also another recommended way is for us to actually publish distro packages for mov-cli. User software like mov-cli should be installed and managed by the distro's package manager. 

I can work on this, I'm gonna try and create a package for Arch Linux and somehow ask the previous maintainer for access to the current package.

**Comment by THEGOLDENPRO** [comment]
Actually nvm I can actually package ``mov-cli`` I think, the other package was ``mov-cli-git``.

**Comment by THEGOLDENPRO** [comment]
@bachig26 I was able to get mov-cli running in a fresh Alpine Linux docker container and I seem to be getting no errors, I wonder what's up with iSH Shell. Maybe you can try this again with my steps below.

![image](https://github.com/mov-cli/mov-cli/assets/66202304/54d324d1-5761-4ffe-a53e-e5542083999a)

Here were my steps:
```sh
apk update && apk upgrade

apk add python3 fzf pipx
```
```sh
# You will need to add this to something like .bashrc however, I'm just exporting it on the fly for testing.
export PATH=$PATH:~/.local/bin
```
```sh
pipx install mov-cli
```

**Comment by ananasmoe** [comment]
> ```shell
> apk add python3 fzf pipx
> ```

I looks like pipx isn't a package in version 3.24.3.

![IMG_0027](https://github.com/mov-cli/mov-cli/assets/132799819/456f05af-f2bb-4f48-97ba-1d0dfe134032)

**Comment by THEGOLDENPRO** [comment]
ah I see. In the latest versions of Alphin they seem to follow [PEP 668](https://peps.python.org/pep-0668/) so pip is blocked from installing user packages just like bachig26 stated.

**Comment by THEGOLDENPRO** [comment]
Has this been tested again. @r3tr0ananas

**Comment by ananasmoe** [comment]
I can't test it because the beta is still full. @bachig26 would have to test it

**Comment by bachig26** [comment]
> I can't test it because the beta is still full. @bachig26 would have to test it

I can't install in iSH beta, since iSH crashes everytime when I tried to install using pipx. It's weird with the latest mov-cli version, I'm not sure why.

**Comment by ananasmoe** [comment]
> > I can't test it because the beta is still full. @bachig26 would have to test it
> 
> I can't install in iSH beta, since iSH crashes everytime when I tried to install using pipx. It's weird with the latest mov-cli version, I'm not sure why.

I also can't install the testflight version of iSH.

![image](https://github.com/mov-cli/mov-cli/assets/132799819/92e17394-5bdc-4cec-a5d3-486dac273090)

**Comment by THEGOLDENPRO** [comment]
This honestly is just an iOS moment. Can't you side load? Like genuine question I'm not trying to shit on iOS lmao.

**Comment by ananasmoe** [comment]
> This honestly is just an iOS moment. Can't you side load? Like genuine question I'm not trying to shit on iOS lmao.

Well with the new eu act i thought i could but them fuckers only allowed 'Apple-certified app stores'.

**Comment by THEGOLDENPRO** [comment]
> > This honestly is just an iOS moment. Can't you side load? Like genuine question I'm not trying to shit on iOS lmao.
> 
> Well with the new eu act i thought i could but them fuckers only allowed 'Apple-certified app stores'.

😭😭😭

**Comment by ananasmoe** [comment]
![image](https://github.com/mov-cli/mov-cli/assets/132799819/136ab3b6-f762-45e6-8615-c3275e71084a)

I got iSH on testflight let's go

**Comment by bachig26** [comment]
> ![image](https://github.com/mov-cli/mov-cli/assets/132799819/136ab3b6-f762-45e6-8615-c3275e71084a)
> 
> I got iSH on testflight let's go

Awesome 🍻

**Comment by ananasmoe** [comment]
Installing mov-cli on the testflight version worked fine.

Only thing is that:

![passt](https://github.com/mov-cli/mov-cli/assets/132799819/ce25e1be-809c-45a8-9fc8-849bbd175524)

but the url was still copied to the clipboard so it would work.

**Comment by THEGOLDENPRO** [comment]
@r3tr0ananas I haven't used the ios version of mov-cli but wouldn't it be better to switch back to the clickable link. Wasn't the clipboard alternative only required because of the links vadapav were returning?

**Comment by ananasmoe** [comment]
> @r3tr0ananas I haven't used the ios version of mov-cli but wouldn't it be better to switch back to the clickable link. Wasn't the clipboard alternative only required because of the links vadapav were returning?

It was because of vidsrc.to, but i guess we could do that.

**Comment by THEGOLDENPRO** [comment]
Maybe you can have both in the case a link is un-clickable. Not sure how you would detect that though.

**Comment by ananasmoe** [comment]
> Maybe you can have both in the case a link is un-clickable. Not sure how you would detect that though.

It only broke when a ';' or ':' was in the link, so we could check if they contain these characters and paste it in the clipboard.

**Comment by ananasmoe** [comment]
@bachig26 I'll close this. If you still experience issues, please reopen this issue.

**Comment by THEGOLDENPRO** [comment]
so the commands in the wiki are correct?
