### ISSUE TITLE
multiselect play

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#264]
**Describe the feature/change you'd like.**
@THEGOLDENPRO @r3tr0ananas can you look into the possibility of selecting multiple items from the search results and play it as an playlist?

for example, selecting few videos from the search results from the youtube plugin or selecting few episodes from the films plugin, etc. to make it as an playlist.

**Comment by THEGOLDENPRO** [comment]
Yeah I can look into this.

**Comment by THEGOLDENPRO** [comment]
This won't be possible but when the range feature is worked on you'll be able to queue multiple episodes of a particular show.
