### ISSUE TITLE
return to the previous page after player exit

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#265]
**Describe the feature/change you'd like.**
after the player is closed/exited, the program should return to the previous page, for example like the season page in films/anime plugin and the search results page in the youtube plugin instead of completely quiting the program in the terminal.

**Comment by THEGOLDENPRO** [comment]
If your goal is to watch another episode or search again, that functionality will be present in watch options from this issue #226.

**Comment by THEGOLDENPRO** [comment]
watch options have been added v4.2
