### ISSUE TITLE
update availability doesn't work

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#270]
**Describe the bug:**
[mov-cli > utils > version.py](https://github.com/mov-cli/mov-cli/blob/v4/mov_cli/utils/version.py)

as far as i know this should show a notification when the mov-cli run at the terminal indicating that there's a new update is available if there's any new version.

but it hasn't been worked with v4 since it's been released to pypi.

@THEGOLDENPRO please have a look at this.

**Comment by THEGOLDENPRO** [comment]
It's been working perfectly for me. When a new version is available it will notify you when you run the mov-cli command. This has worked for me in multiple versions since v4 without fail.

Could you downgrade to an older version and try and reproduce it?

**Comment by THEGOLDENPRO** [comment]
could anyone else also try and reproduce this issue

**Comment by bachig26** [comment]
> Could you downgrade to an older version and try and reproduce it?

yes, i'll try it.

**Comment by bachig26** [comment]
> Could you downgrade to an older version and try and reproduce it?

i just downgraded to 4.2.0 and tried, it's showing now.
it's really weird for me, since it never showed for me before.

i'll close it now, maybe if similar thing happens, i'll try to open it again with a log & terminal output.
