### ISSUE TITLE
ability to view season and episodes in tree view

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#271]
**Describe the feature/change you'd like.**

will it be possible to have the content listing in the form of tree view, so it's easy to fallback to different seasons better.

i think there might be limitation with `fzf`, but i not sure, please have a look if there's something can be done for this idea.

**Comment by THEGOLDENPRO** [comment]
Umm, I'm not sure if this is possible and I feel as if this would add more complexity.

**Comment by THEGOLDENPRO** [comment]
Yeah I don't think this will be possible and I want to keep the cli codebase to a minimal so I'm closing this.
