### ISSUE TITLE
[BUG] "mov-cli --edit" outputs "sh: 1: nano: not found"

### ISSUE THREAD

**Issue by IceAsteroid** [mov-cli/mov-cli#272]
**Describe the bug:**
I've set up the env variable ```export EDITOR=nvim```

In order, if in any case, that lower case  for it would work, I also set up ```export editor=nvim```, but still no luck.

**Expected behavior:**
Being able to switch to another editor like vim.

**Error:**
Good Morning, user.
    It's 10:20 AM on a beautiful Thursday! 

- Hint: mov-cli -s films mr.robot
- Hint: mov-cli -s anime chuunibyou demo take on me

[DEBUG] (mov_cli) - Config -> {'version': 1, 'player': 'mpv', 'debug': True, 'ui': {'fzf': True}, 'plugins': {'test': 'mov-cli-test'}}
sh: 1: nano: not found

```python
Python 3.12.2 (main, Feb 15 2024, 06:47:30) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Platform (please complete the following information):**
 - OS: VoidLinux
 - Version: 6.6.21_1

**Additional context / possible cause or solution:**
Add any other context about the problem here or possible causes and solutions.

**Version**
4.2.5

**Comment by ananasmoe** [comment]
You need to set the editor inside the config, but you can't edit it because nano is the standard editor and you don't have it.

**Comment by ananasmoe** [comment]
You can also edit the config file, see the [Wiki](https://github.com/mov-cli/mov-cli/wiki/Configuration#introduction)

**Comment by THEGOLDENPRO** [comment]
Yeah didn't add support for the ``EDITOR`` environment variable yet. I will add it soon. 👍

**Comment by THEGOLDENPRO** [comment]
For now you can do:
```sh
{your-editor} ~/.config/mov-cli/config.toml
```

**Comment by IceAsteroid** [comment]
Ok, copy that :)

Setting up ```editor = "nvim"``` in the config.toml works

**Comment by ananasmoe** [comment]
Is now added with this commit: https://github.com/mov-cli/mov-cli/commit/3cd9b9c556f0fc4cef32fa9bd859d42e1a4f588b
