### ISSUE TITLE
[FEATURE] Make editor config key fallback to ``EDITOR`` env var on Linux.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli#274]
At the moment the default value for the editor in mov-cli is `nano` on Linux but some may not use nano or have it installed so it's good practice to fallback to the editor set in the user's ``EDITOR`` environment variable if available. If this isn't available fallback to the usual `nano` editor.

This change should be done within the editor property method in the config class.

**Comment by ananasmoe** [comment]
Added with this commit: https://github.com/mov-cli/mov-cli/commit/3cd9b9c556f0fc4cef32fa9bd859d42e1a4f588b
