### ISSUE TITLE
[OFF-TOPIC] Need MacOS testers.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli#275]
I had my classmate try out mov-cli on his Apple Silicon MacBook and it didn't go well 💀

I would try and debug it but I obviously don't have access to his laptop and I don't want to waste his time guiding him through discord so anyone with spare time and a Mac please try the project.

One of the issues we ran into was the config file not being created in the correct location. I think it has to do with the space in the MacOS config path (check out the config wiki if you don't know what I mean) and MacOS not phrasing it correctly.

**Comment by ananasmoe** [comment]
Hackintosh

![ab4e33b2efc814daf4e37b119202b48f(1)](https://github.com/mov-cli/mov-cli/assets/132799819/97ce38e6-49f0-4fcd-9f8a-336471f8a982)

**Comment by maiavixen** [comment]
On my M2 Pro, MacBook Pro, mov-cli config is in `~/Library/Application Support/mov-cli/config.toml`. Works fine for me

**Comment by THEGOLDENPRO** [comment]
Found the issue and confirmed that it works on my friends macbook after patching it. I'll publish a fix very soon.
