### ISSUE TITLE
How to install on macos?

### ISSUE THREAD

**Issue by PogusTheWhisper** [mov-cli/mov-cli#279]
How to install on macos?

**Comment by THEGOLDENPRO** [comment]
mov-cli does work on MacOS but you require a couple of prerequisites. Also I may not be able to guide you exactly step by step as I don't own a Mac nor am I familiar enough with the MacOS.

You first will need [homebrew](https://brew.sh/) installed, then once installed you can install [iina](https://formulae.brew.sh/cask/iina) (mpv media player for mac) and [fzf](https://formulae.brew.sh/formula/fzf#default).

Now you can install mov-cli via pip:
```sh
pip install mov-cli -U
```
Then [install a plugin](https://github.com/mov-cli/mov-cli/wiki/Plugins#%EF%B8%8F-how-to-install-plugins) of your choice and all should be good.

**Comment by THEGOLDENPRO** [comment]
How did this go btw?

**Comment by PogusTheWhisper** [comment]
Yes, It work!!!
