### ISSUE TITLE
theflix shows incorrect number of episodes

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#28]
while I was watching south park I noticed that "theflix" showed an incorrect total number of episodes
![image](https://user-images.githubusercontent.com/108033555/181803411-38aa39a8-a43f-42cc-8564-5899dfdccc6e.png)
this problem doesn't seem to happen in others providers, take "actvid" as an example
![image](https://user-images.githubusercontent.com/108033555/181803731-0e33a92c-f246-4662-a412-32a10d029253.png)
at first, I through theflix didn't have the full season, but it doesnt seem to be the case considering that if I type a number between 12-17 i can actually watch it.
![image](https://user-images.githubusercontent.com/108033555/181804468-f0c28b31-3719-4baf-a68b-91353ddcb1de.png)
I also tested it with breaking bad and it says seasons one has 12 episodes, when in reality it only have 7

**Comment by Poseidon444** [comment]
Yea, theflix provides the total number of episodes in the whole series,I just divided the total number of episodes by the number of seasons to get an average.

**Comment by ghost** [comment]
Looks like it has been explained
