### ISSUE TITLE
[FEATURE] shell completions as  separate files

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#281]
**Describe the feature/change you'd like.**

the completions are part of the executable and they need to be run in order to be generated. 

This complicates packaging and contributing to them. They should just be separate files.

**Comment by THEGOLDENPRO** [comment]
Never messed around with shell completions so I have no idea how to do this. [Typer](https://typer.tiangolo.com/) is what handles shell completions.

However it seems mov-cli [version 4.2.11](https://github.com/mov-cli/mov-cli/commit/5f7cb58d9f20d0c505bb5390477b940bfc98a955) broke auto complete after switching to typer 0.11.0 and above.

**Comment by THEGOLDENPRO** [comment]
Getting this to work with typer would be great.

**Comment by ghost** [comment]
in yt-dlp the completions are generated by scripts that can be run without been installed. You could just add scripts like that with relative module loading, that are not included in the final installation. This way we can package the completions and they will always be up to date

**Comment by ananasmoe** [comment]
![image](https://github.com/mov-cli/mov-cli/assets/132799819/3c31a886-c213-4103-8ac2-4c4e4b6b916d)
