### ISSUE TITLE
add an arg to list the installed scrapers

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#283]
**Describe the feature/change you'd like.**
at the moment, the plugins has it's default scrapers, so we're calling it just using the keyword like `films`, `youtube`, etc.
but if the default scraper doesn't work. most people using don't remember having other scrapers available and one needs to look through the plugins repo or most of will open an issue.

if an arg specifically available to list out the installed/available scrapers in the plugins, will make it easier to use without exiting the terminal.
 for example, after calling the arg in mov-cli like `mov-cli --list-scrapers` or `mov-cli -ls`;
then it could show the available scrapers like below:
```
films
{namespace}.{scraper}
{namespace}.{scraper}

youtube
{namespace}.{scraper}

anime
{namespace}.{scraper}
{namespace}.{scraper}
```
might be useful also by indicating which one is the default scraper now.

**Comment by ananasmoe** [comment]
I'll look in to it.

**Comment by ananasmoe** [comment]
Will be added with v4.3.

**Comment by ananasmoe** [comment]
https://github.com/mov-cli/mov-cli/commit/0632aad8aafc1da9e9a84ab465f66ebd99067131
