### ISSUE TITLE
`--version` doesn't list the plugin's version

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#284]
**Describe the feature/change you'd like.**
please also add the function that `mov-cli --version` arg, can also display the installed plugin's version.

**Comment by ananasmoe** [comment]
Will be added with v4.3.

**Comment by ananasmoe** [comment]
https://github.com/mov-cli/mov-cli/commit/0632aad8aafc1da9e9a84ab465f66ebd99067131

**Comment by bachig26** [comment]
> [0632aad](https://github.com/mov-cli/mov-cli/commit/0632aad8aafc1da9e9a84ab465f66ebd99067131)

```
mov-cli --version

Good Night, USER.
    It's 06:38 AM on a gorgeous Wednesday!

-> Version: 4.3.0
```
it doesn't show the versions of plugins.
is it because it's made available in the list plugins arg?
```
mov-cli -lp
- mov-cli-test (test) [1.1.0]
  - test
- mov-cli-films (films) [1.3.7]
  - vidsrcme
  - vadapav
  - vidsrcto
- mov-cli-anime (anime) [1.1.0]
  - anitaku
- mov-cli-youtube (youtube) [1.1.2]
- mov-cli-files (files) [1.0.3]
  - boilerplate
 ```

**Comment by ananasmoe** [comment]
Yes
