### ISSUE TITLE
Does this work with MPC-BE or is mpv a requirement?

### ISSUE THREAD

**Issue by gursuj** [mov-cli/mov-cli#29]

**Comment by gursuj** [comment]
So I installed mpv but it doesn't detect it. 
`Could not play : MPV or VLC not found | [WinError 2] The system cannot find the file specified`

Do I need to specify the mpv path?

**Comment by Poseidon444** [comment]
is mpv on path? I recommend you uninstall it and install using scoop or chocolatey

**Comment by gursuj** [comment]
Reinstalled with chocolatey but still getting the same error. Reinstalling mov-cli didn't work too.
This is on windows btw.

**Comment by Poseidon444** [comment]
does typing mpv on the terminal display some text or open it?

**Comment by gursuj** [comment]
shows some text

**Comment by Poseidon444** [comment]
some text as in "'mpv' command not found" or "mpv *.*.* Copyright..."

**Comment by gursuj** [comment]
Sorry, should have clarified. It shows the copyright & other info

**Comment by gursuj** [comment]
> is mpv on path? 

I just remembered this means the Windows Environment Variable. Apologies for the troubles. Works like a charm
