### ISSUE TITLE
[BUG] getting mov-cli: command not found in terminal after successfull installation

### ISSUE THREAD

**Issue by Jagadishwar49** [mov-cli/mov-cli#303]
**Describe the bug:**
getting mov-cli: command not found in terminal after successfull installation

![mov-cli](https://github.com/mov-cli/mov-cli/assets/73735680/9b0632d7-5a4e-4f71-9953-591ceb903d30)

OS : linux Mint
Python Version : 3.10

Please help me with this issue

**Comment by ananasmoe** [comment]
is `~/.local/bin` in your path?

**Comment by Jagadishwar49** [comment]
Yes after reinstalling and restart it worked

**Comment by Jagadishwar49** [comment]
Yes after reinstalling and restart it worked
