### ISSUE TITLE
Multiple episode download

### ISSUE THREAD

**Issue by girvindillon** [mov-cli/mov-cli#311]
**Before asking:**
Check through [Issues](https://github.com/mov-cli/mov-cli/issues) and closed ones too if your question was already answered.

**Question:**
Is there a way to queue a download for an entire season, or can you only download one episode at a time manually?

**Comment by ananasmoe** [comment]
Currently you only can download one media at a time.

**Comment by girvindillon** [comment]
Understood, thank you. Hopefully that will be added in the future.
