### ISSUE TITLE
[BUG] Changing the save directory seems to do nothing.

### ISSUE THREAD

**Issue by girvindillon** [mov-cli/mov-cli#312]
**Describe the bug:**
 When I use -d the desired download is put in the same directory as mov.cli.exe rather than in the directory specified in the config file.

**Expected behavior:**
 The directory provided in the config file should be where the desired episode is saved to.

**Steps to reproduce:**
 Use -d on anything using any plugin. Operating system is windows.

**Screenshots:**
 N/A

**Logs:**

I can't seem to figure out how to get the debug file.

**Platform:**

 - OS:  Windows
 - Version:  10

**Additional context / possible cause or solution:**

**Version**
 Latest version of mov-cli.exe

**Comment by ananasmoe** [comment]
I can't reproduce this issue, could you send your config file?

**Comment by girvindillon** [comment]
Yes, where is it stored on windows? I have only edited it through the -e argument.

**Comment by ananasmoe** [comment]
> Yes, where is it stored on windows? I have only edited it through the -e argument.

You can just copy the lines of the config from the -e argument and paste them into GitHub.

**Comment by girvindillon** [comment]
Here you go:

```python
[mov-cli]
version = 1
player = "mpv"
debug = false
# parser = "lxml"
# editor = "nano"
skip_update_checker = false

# [mov-cli.ui]
# fzf = true

[mov-cli.plugins] # E.g: namespace = "package-name"
test = "mov-cli-test"
film = "film-central"
anime = "otaku-watcher"

# [mov-cli.scrapers]
# default = "films"

# [mov-cli.http] # Don't mess with it if you don't know what you are doing!
# headers = { User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" }

# [mov-cli.downloads] # Do not use backslashes use forward slashes
# save_path = "C:/Users/nivri/Videos/Mov-Cli Downloads"

# [mov-cli.quality]
# resolution = 1080
```

**Comment by ananasmoe** [comment]
You have to remove the # from `[mov-cli.downloads]` and `save_path`

**Comment by girvindillon** [comment]
Ah I'm a moron, didn't look at that lol. Thanks.
