### ISSUE TITLE
packet corrupt

### ISSUE THREAD

**Issue by BLUERIUM** [mov-cli/mov-cli#319]
every time i download a movie i get lots of packet corrupt errors and it ends up downloading a file that doesn't open.

![image](https://github.com/mov-cli/mov-cli/assets/119827195/6fb2223e-b95b-49ef-b834-891cbb14d820)

**Comment by ananasmoe** [comment]
This is not a mov-cli issue, it's the sites fault.

**Comment by BLUERIUM** [comment]
ok
