### ISSUE TITLE
[BUG]  On Arch Linux, plugins only work only from within virtual environment

### ISSUE THREAD

**Issue by mercifulboss** [mov-cli/mov-cli#320]
**Describe the bug:**
1. Install Arch linux
2. Install `mov-cli` from AUR using yay
3. Follow instructions to install mov-cli-youtube from here: https://github.com/mov-cli/mov-cli-youtube
4.  doesn't work because Arch doesn't allow direct `pip installs`, install is instead directly into venv
5. try to launch using command provided to test if it works `mov-cli -s youtube nyan cat`
6. gives error: 
![image](https://github.com/mov-cli/mov-cli/assets/90151527/f5ed1692-1198-4c66-a76c-ed8f1ced083d)
7. decide to test with same venv as it was installed in `venv/bin/activate`. Works
8. Very inconvenient and would be nice for it to work without having to launch a venv every time
 

**Expected behavior:**
Using `mov-cli -s youtube nyan cat` should allow the plugin to work. It doesn't unless launched in venv

**Screenshots:**
![image](https://github.com/mov-cli/mov-cli/assets/90151527/bd78ab22-7ac9-4afd-97bd-e4c9c014f90a)

**Platform:**

OS: Arch Linux x86_64 
Kernel: 6.9.2-arch1-1 
DE: Plasma 6.0.5 
 
**Additional context / possible cause or solution:**

**Version**
4.3.15

**Comment by ananasmoe** [comment]
> **Describe the bug:**
> 
>     1. Install Arch linux
> 
>     2. Install `mov-cli` from AUR using yay
> 
>     3. Follow instructions to install mov-cli-youtube from here: https://github.com/mov-cli/mov-cli-youtube
> 
>     4. doesn't work because Arch doesn't allow direct `pip installs`, install is instead directly into venv
> 
>     5. try to launch using command provided to test if it works `mov-cli -s youtube nyan cat`
> 
>     6. gives error:
>        ![image](https://private-user-images.githubusercontent.com/90151527/336996947-f5ed1692-1198-4c66-a76c-ed8f1ced083d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MjMxMDAsIm5iZiI6MTcxNzYyMjgwMCwicGF0aCI6Ii85MDE1MTUyNy8zMzY5OTY5NDctZjVlZDE2OTItMTE5OC00YzY2LWE3NmMtZWQ4ZjFjZWQwODNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIxMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZmE3NjNjNDVhY2NlMzVlNmRhYjdiZGNjZTQ0ODQzZTIwMjQzNTA5YzEwMTMxZDI0NGI3OTQyZDViZjQyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qqHiwpcX9g8lRHl9RaV6NxBKYTzxwd07BsoMli1zYjE)
> 
>     7. decide to test with same venv as it was installed in `venv/bin/activate`. Works
> 
>     8. Very inconvenient and would be nice for it to work without having to launch a venv every time
> 
> 
> **Expected behavior:** Using `mov-cli -s youtube nyan cat` should allow the plugin to work. It doesn't unless launched in venv
> 
> **Screenshots:** ![image](https://private-user-images.githubusercontent.com/90151527/336997743-bd78ab22-7ac9-4afd-97bd-e4c9c014f90a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MjMxMDAsIm5iZiI6MTcxNzYyMjgwMCwicGF0aCI6Ii85MDE1MTUyNy8zMzY5OTc3NDMtYmQ3OGFiMjItN2FjOS00YWZkLTk3YmQtZTRjOWMwMTRmOTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIxMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOWMxODY4OTAxZWUwMzdlNmM0ZjVmNGUzMDk0MDQwMDNiMDljMDIxYjIzNjMwMjIxOWIyYzY0MWQ4ZThkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.832uqVrhPZQTHmNQ2xX4dakiuOobM4MSm6eAgKhsQ1Y)
> 
> **Platform:**
> 
> OS: Arch Linux x86_64 Kernel: 6.9.2-arch1-1 DE: Plasma 6.0.5
> 
> **Additional context / possible cause or solution:**
> 
> **Version** 4.3.15

There is a aur package: [python-mov-cli-youtube](https://aur.archlinux.org/packages/python-mov-cli-youtube)

**Comment by mercifulboss** [comment]
> > **Describe the bug:**
> > ```
> > 1. Install Arch linux
> > 
> > 2. Install `mov-cli` from AUR using yay
> > 
> > 3. Follow instructions to install mov-cli-youtube from here: https://github.com/mov-cli/mov-cli-youtube
> > 
> > 4. doesn't work because Arch doesn't allow direct `pip installs`, install is instead directly into venv
> > 
> > 5. try to launch using command provided to test if it works `mov-cli -s youtube nyan cat`
> > 
> > 6. gives error:
> >    ![image](https://private-user-images.githubusercontent.com/90151527/336996947-f5ed1692-1198-4c66-a76c-ed8f1ced083d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MjMxMDAsIm5iZiI6MTcxNzYyMjgwMCwicGF0aCI6Ii85MDE1MTUyNy8zMzY5OTY5NDctZjVlZDE2OTItMTE5OC00YzY2LWE3NmMtZWQ4ZjFjZWQwODNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIxMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZmE3NjNjNDVhY2NlMzVlNmRhYjdiZGNjZTQ0ODQzZTIwMjQzNTA5YzEwMTMxZDI0NGI3OTQyZDViZjQyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qqHiwpcX9g8lRHl9RaV6NxBKYTzxwd07BsoMli1zYjE)
> > 
> > 7. decide to test with same venv as it was installed in `venv/bin/activate`. Works
> > 
> > 8. Very inconvenient and would be nice for it to work without having to launch a venv every time
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Expected behavior:** Using `mov-cli -s youtube nyan cat` should allow the plugin to work. It doesn't unless launched in venv
> > **Screenshots:** ![image](https://private-user-images.githubusercontent.com/90151527/336997743-bd78ab22-7ac9-4afd-97bd-e4c9c014f90a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MjMxMDAsIm5iZiI6MTcxNzYyMjgwMCwicGF0aCI6Ii85MDE1MTUyNy8zMzY5OTc3NDMtYmQ3OGFiMjItN2FjOS00YWZkLTk3YmQtZTRjOWMwMTRmOTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIxMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOWMxODY4OTAxZWUwMzdlNmM0ZjVmNGUzMDk0MDQwMDNiMDljMDIxYjIzNjMwMjIxOWIyYzY0MWQ4ZThkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.832uqVrhPZQTHmNQ2xX4dakiuOobM4MSm6eAgKhsQ1Y)
> > **Platform:**
> > OS: Arch Linux x86_64 Kernel: 6.9.2-arch1-1 DE: Plasma 6.0.5
> > **Additional context / possible cause or solution:**
> > **Version** 4.3.15
> 
> There is a aur package: [python-mov-cli-youtube](https://aur.archlinux.org/packages/python-mov-cli-youtube)

Hello,

Thank you for your response.

I installed the package through the AUR and it works. The plugins don't work since they require pip to install and on arch pip doesn't work.

Here is the message it gives when trying to install directly from pip:

![image](https://github.com/mov-cli/mov-cli/assets/90151527/03568461-52d3-4ad8-a67b-04c7fcd51e23)


For this to work one needs to spin up an venv environment which is inconvenient. 

EDIT: I missed the AUR package! Thanks! Would it be possible to provide links on the main page to the repository? That would be helpful for those of us on arch!

**Comment by THEGOLDENPRO** [comment]
> Would it be possible to provide links on the main page to the repository? That would be helpful for those of us on arch!

will do
