### ISSUE TITLE
[FEATURE] fzf image support

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli#321]
![image](https://github.com/mov-cli/mov-cli/assets/66202304/41d70030-4df5-458b-b891-9c0b02340b1d)

Here's what we need to do:
- [x] Move ``image_url`` in `ExtraMetadata` to `Metadata` as an optional parameter. (This is because we'll have to get the image of each metadata pretty quick and ExtraMetadata is designed to house metadata that is expensive to get in terms of time hence why we assign a function or lambda expression to it)
- [x] On prompt dump the image url of each metadata in temp cache.
- [x] Create another mov-cli command like `mov-cli-preview` that will take the metadata unique ID like this `mov-cli-preview image {id}`. Then that command should call the relevant terminal image viewer command to display the image.
- [x] That `mov-cli-preview` command will then be added as the fzf `preview` argument. Fzf will call this each time a choice is cycled through with the name of the choice being passed via curly brackets `{}` so the command would look like this in the argument: `mov-cli-preview image {}`
- [x] support for non kitty terminals https://github.com/mov-cli/mov-cli/commit/9c8920b2e2462973967f9e1c651ea8720e3d2902
- [x] add config key
- [x] document the feature
- [x] add ``--image`` flag to enable fzf image preview

**Comment by THEGOLDENPRO** [comment]
Currently only supports the kitty terminal.

**Comment by THEGOLDENPRO** [comment]
@r3tr0ananas If you could possibly look into support for other terminals outside of kitty that would be amazing.

I guess my messages from before will help:

![image](https://github.com/mov-cli/mov-cli/assets/66202304/f9219443-22ca-43bd-9a9f-37371d7a2fcd)

**Comment by THEGOLDENPRO** [comment]
Also doesn't work with soundcloud images but I think that's just a bug somewhere with the preview command, I can look into that one.

**Comment by ananasmoe** [comment]
Will do

**Comment by THEGOLDENPRO** [comment]
Releasing on v4.4 of mov-cli. #298
