### ISSUE TITLE
Player options

### ISSUE THREAD

**Issue by rabaimorp** [mov-cli/mov-cli#323]
I always add additonal flags when I normally play videos.
Example:
ffplay -fflags +nobuffer -volume 9 -loop 0 <video>
mpv --fs --volume=30 --loop <video>

There is an option in the config file to define the player, but putting my flags after it like a command doesn't work. (Maybe I'm just too stupid to figure how to do it but in that case documentation would be great.)

**Something working like this in the config would be great:**
player = "ffplay"
player-flags = "-fflags +nobuffer -volume 9 -loop 0"

**Comment by THEGOLDENPRO** [comment]
You're not stupid player args in the player key don't work. I had planned to add a feature like this but I almost forgot.

I'll squeeze it into the [feature list](https://github.com/mov-cli/mov-cli/issues/298) for the next major mov-cli version (v4.4) so hopefully you'll be seeing it soon.

**Comment by THEGOLDENPRO** [comment]
Player args now exist in the [latest version](https://github.com/mov-cli/mov-cli/releases/tag/4.4) of mov-cli. Check out the wiki on how to use it: https://github.com/mov-cli/mov-cli/wiki/Configuration#player-args

I hope this helps with your issue.

**Comment by rabaimorp** [comment]
The wiki could give an example for more args:
`args = ['--loop', '--volume-max=250', '--fs']`
maybe something like this, so I'ts more obvious that its not like normal cli when you just separate options with spaces.

**Comment by THEGOLDENPRO** [comment]
> The wiki could give an example for more args: `args = ['--loop', '--volume-max=250', '--fs']` maybe something like this, so I'ts more obvious that its not like normal cli when you just separate options with spaces.

I could add that.
