### ISSUE TITLE
Can't play in mpv player for movie streaming 

### ISSUE THREAD

**Issue by Ryouki2004** [mov-cli/mov-cli#326]
- Go to "mov-cli -e"
- Change the mpv to vlc
- Ctrl + O , enter and Ctrl X
- Download vlc player
- mov-cli -s films (name of the movie)

**Comment by ananasmoe** [comment]
Send a full log please.

**Comment by THEGOLDENPRO** [comment]
Do you mean "can't play in vlc player"?

**Comment by THEGOLDENPRO** [comment]
Have you figured out the issue?

**Comment by ananasmoe** [comment]
Stale
