### ISSUE TITLE
[BUG] Using IINA as a player leads to crash 

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#329]
**Describe the bug:**

Using `--player iina` leads to an error, resulting in a crash and not opening the video.

**Expected behavior:**

IINA opens and plays the selected video.

**Steps to reproduce:**

1. `mov-cli -syoutube -piina <some search>` (or set the flags in the config file).
2. Select video.

**Logs:**
```python
File "mov_cli/players/iina.py", line 26, in __init__
    self.display_name = Colours.GREY.apply("IINA")
    ^^^^^^^^^^^^^^^^^
AttributeError: property 'display_name' of 'IINA' object has no setter
```

**Platform:**

 - OS: macOS
 - Version: 4.4.1

**Additional context / possible cause or solution:**

The problem seems to be that `display_name` is not settable, yet line 26 in `iina.py` attempts to do so. I compared this with the other player files and the parent class, which seem to just override the property. If you do the same thing in `iina.py`, it works.

Here's a patch that works for me. I'm not very familiar with Python, so forgive me if this is not the idiomatic way to do it.

```patch
diff --git a/mov_cli/players/iina.py b/mov_cli/players/iina.py
index e986481..56c2216 100644
--- a/mov_cli/players/iina.py
+++ b/mov_cli/players/iina.py
@@ -23,8 +23,6 @@ class IINA(Player):
         debug: bool = False, 
         **kwargs
     ) -> None:
-        self.display_name = Colours.GREY.apply("IINA")
-
         super().__init__(
             platform = platform, 
             args = args, 
@@ -32,6 +30,10 @@ class IINA(Player):
             args_override = args_override
         )
 
+    @property
+    def display_name(self) -> str:
+        return Colours.GREY.apply("IINA")
+
     def play(self, media: Media) -> Optional[subprocess.Popen]:
         """Plays this media in the IINA media player for MacOS."""
```

**Version**

**Checklist**
- [x] I have added logs.
- [x] I have added my platform.
- [x] I have added my version number.
- [x] I am sure that this issue is not related to a plugin.

**Comment by ananasmoe** [comment]
Should be fixed now.

<img src="https://github.com/mov-cli/mov-cli/assets/132799819/6f5a5083-bb79-4dc7-bc32-8a0fc8ffad23" width="200">
