### ISSUE TITLE
[minor BUG] good night in the day

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#333]
```
Good Night, XXX.
    It's 12:36 PM on a beautiful Tuesday!
```

It's not night... It's probably one of the libraries doing this. It's up to you to report it upstream. I'm assuming this is a simple bug.

**Comment by THEGOLDENPRO** [comment]
What was the actual time and date for you then?

**Comment by ananasmoe** [comment]
https://github.com/mov-cli/mov-cli/commit/4b172828122fb48f9e98e26f3401fd76705a21e5

<img src="https://github.com/mov-cli/mov-cli/assets/132799819/6f5a5083-bb79-4dc7-bc32-8a0fc8ffad23" width="200">

**Comment by ghost** [comment]
That was the correct date and time. It seams to think that PM means night.

**Comment by THEGOLDENPRO** [comment]
Yeah that was correct.

**Comment by THEGOLDENPRO** [comment]
Wait what was the actual time for you? (24 hour format)

**Comment by ghost** [comment]
12 hour format
4.4.4 still does it

```
Good Night, XXX
    It's 12:01 PM on a beautiful Wednesday!
```

**Comment by ghost** [comment]
it was 12:00 in 24h format.

**Comment by ananasmoe** [comment]
> 12 hour format 4.4.4 still does it
> 
> ```
> Good Night, XXX
>     It's 12:01 PM on a beautiful Wednesday!
> ```

4.4.5 is the latest

**Comment by ghost** [comment]
ok, it seams fixed.
