### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Iva120** [mov-cli/mov-cli#340]
I recently have installed mov-cli on my OS and followed the wiki word for word on adding the mov-cli-youtube plugin, however when edited config.toml and actually tried to use the plugin, I got this error message despite the fact that mov-cli-youtube and mov-cli are in the same folder. How do I fix this?
![Screenshot_20240716_225708](https://github.com/user-attachments/assets/ad164bb2-d193-4f6f-9bb4-ae49ef8735eb)

**Comment by ananasmoe** [comment]
Are you using pipx or normal pip?

You have `mov-cli-youtube` installed?

**Comment by ananasmoe** [comment]
stale

**Comment by AimbotBurger** [comment]
I accidently managed to replicate this, or in other words, I'm stuck with this error.

Currently on windows, tried to install several past versions of the plugin and mov-cli without any success.
Updated everything from Scoop and updated each dependency as well without any sucess either.

Let me know if there is a way to debug or if there is a way to provide further detail on the issue at hand.
