### ISSUE TITLE
[minor BUG] the link for 4.4.11 still valid

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#350]
As of writing, i can still download 4.4.11 that was yanked out. https://github.com/mov-cli/mov-cli/archive/refs/tags/4.4.11.tar.gz

The main page sais 23 releases and bellow it 22 releases. Something is bugged up.

**Comment by ananasmoe** [comment]
I deleted the 4.4.11 tag.

**Comment by THEGOLDENPRO** [comment]
Thanks for that. 👍 

That was my mistake.
