### ISSUE TITLE
[BUG] Can't find scraper

### ISSUE THREAD

**Issue by yviskos** [mov-cli/mov-cli#369]
**Describe the bug:**
I followed the instructions to download mov-cli and the mov-cli-youtube, copying the commands in the documentation exactly. I put `[mov-cli.plugins]
youtube = "mov-cli-youtube"`
In my config.toml, however I get met with an error when I type the command `mov-cli -s --debug youtube blender studio` stating the scraper didn't exist.
Upon installing mov-cli-files and running `mov-cli -s files "*"` the same issue was occuring
**Mov-cli version:** ``{4.4.15}``

**Expected behaviour:**
I expected to not be met with an error and be able to find and watch videos using mov-cli.

**Steps to reproduce:**
1. Install mov-cli
2. Install the a plugin, namely mov-cli-youtube
3. Add the plugin to your config.toml
4. Attempt to run mov-cli

**Logs:**
```
[ERROR] (mov_cli) - Could not find a scraper by the id 'youtube'! Are you sure the plugin is installed and in your config? Read the wiki for more on that: 'https://github.com/mov-cli/mov-cli/wiki#plugins'.
Available Scrapers -> test.default | test.test

* Did you mean: test.test

[ERROR] (mov_cli) - You must choose a scraper to scrape with! You can set a default scraper with the default key in config.toml.
```

**Platform:**
 - OS: Windows 11 Home
 - Version: 23H2

**Checklist**
- [Yes] I have added logs.
- [Yes] I have added my platform.
- [Yes] I have added my version number.
- [Yes] I am sure that this issue is not related to a plugin.

**Comment by ananasmoe** [comment]
Did you install mov-cli via pipx?

**Comment by yviskos** [comment]
I have tried installing with pipx and pip, both yield the same errors.

**Comment by ananasmoe** [comment]
with pipx you need to do: `pipx inject mov-cli mov-cli-youtube` have you done that?

**Comment by yviskos** [comment]
Yes. Now that I have also cleared the cache, a different error is yielded.
Here are the logs.
```
[INFO] (mov_cli) - [Config] .env file created at 'C:\Users\loven\AppData\Local\mov-cli\.env'.
[CRITICAL] (mov_cli) - [Config] Failed to read config.toml! Please check you haven't made any mistakes in the config.All values will fallback to default.
Error: What? plugins already exists?{'plugins': {'youtube': 'mov-cli-youtube'}} (line 3 column 1 char 46)
```
and here is my config
```
[mov-cli.plugins]
youtube = "mov-cli-youtube"
[mov-cli.plugins]
files = "mov-cli-files"
```

**Comment by ananasmoe** [comment]
```toml
[mov-cli.plugins]
youtube = "mov-cli-youtube"
files = "mov-cli-files"
```

`[mov-cli.plugins]` is only required once.

**Comment by yviskos** [comment]
I'm almost too embarrassed to say thank you.

**Comment by THEGOLDENPRO** [comment]
No worries, so is it all good?
