### ISSUE TITLE
with actvid, sflix or solar u cant download anything

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#37]
![Screenshot 2022-08-07 111821](https://user-images.githubusercontent.com/83706294/183284031-f440fda3-d4bb-491c-9c00-1e457ba7681d.png)

This happens when trying to download with actvid, sflix or solar.

**Comment by Poseidon444** [comment]
Are you on the latest version?

**Comment by ghost** [comment]
It downloads it but gives like a ton of links
