### ISSUE TITLE
All Searches Currently Fail

### ISSUE THREAD

**Issue by HadetTheUndying** [mov-cli/mov-cli#4]
The scraper is currently failing any searches.

Trying:
`./mov-cli $ANYSHOWORMOVIENAME` 

Returns:
`No search results found`

I'm gonna try to fix this on my own and open a PR, but it's a lot to read through. The URL's being scraped still exist, maybe need to add some verbose output for failures. I know gogoplay and gogoanime recently had broken keys for `ani-cli`

**Comment by HadetTheUndying** [comment]
Disregard i did not have bs4 installed:

Fixed by running:

`pip3 install -r requirements.txt`

**Comment by Poseidon444** [comment]
Are you talking about the posix script?
if so yes, the posix script has to undergo some changes as the website has changed a lil_

**Comment by HadetTheUndying** [comment]
The POSIX script

**Comment by Poseidon444** [comment]
Bruh, the how are python modules gonna help you?

**Comment by HadetTheUndying** [comment]
> Bruh, the how are python modules gonna help you?

I assumed that the python scripts were being called by the POSIX script. I hadn't had a chance to actually read it over yet? Are you guys transitioning the project from POSIX to python3? Probably the inconsistency of the POSIX script being able to parse some search request and not others., and had nothing to do with installing the required modules then. Do you want help with documentation?

**Comment by Poseidon444** [comment]
we will be maintaining both the posix and python3 files, also the posix script is still working 
![Uploading image.png…]()
