### ISSUE TITLE
tried on mac book air m1

### ISSUE THREAD

**Issue by aylinturgut0** [mov-cli/mov-cli#46]
downloaded using curl
movie search works, searched american psycho and got this:
https://theflixvd.b-cdn.net/videos/1611591258135_American.Psycho.2000.1080p.BluRay.x264-nikt0.mp4?token=H_c8hdOl9m17S8-kXek28yD8HAU1XZfku942-2XEjjQ&expires=1660
No search results found%

**Comment by ghost** [comment]
You are using the shell version of mov-cli?

**Comment by ghost** [comment]
if so try to use the Python Version of mov-cli.

**Comment by aylinturgut0** [comment]
switched to python from shell, got the errors:
[1] Sorry I don't know that provider!
[2] No such file or directory: '/home/aylinturgut/Documents//mov_cli'

**Comment by R3tr0Ananas** [comment]
Did you test different providers so actvid and so on?

**Comment by ghost** [comment]
So with the current version of mov-cli its wont work. Try my Fork or Wait until @Poseidon444 Merges it and its still doesnt work try a different provider so actvid or sflix or solar.

**Comment by ghost** [comment]
If you still have problems write a message on discord: Ananas#1149

**Comment by R3tr0Ananas** [comment]
Issue is fixed?
