### ISSUE TITLE
mov-cli refuses to work on windows ([WinError 3] The system cannot find the path specified)

### ISSUE THREAD

**Issue by emlano** [mov-cli/mov-cli#49]
It gets as far as to episode selection, or movie selection, but when the stream is selected, it doesn't open the stream with mpv, instead it gives this error and closes. I have another account on the system, named "IIT Work", however mov-cli is not installed in that account. Idk why it is searching for anything there. 

I have already tried uninstalling and reinstalling.
![image](https://user-images.githubusercontent.com/82947413/187036840-f034da87-8abb-4901-86ee-b846f5127460.png)

**Comment by ghost** [comment]
So i can´t recreate it with a different user on windows with cmd or ps.

Maybe try using cmd instead of PS?

**Comment by emlano** [comment]
> So i can´t recreate it with a different user on windows with cmd or ps.
> 
> Maybe try using cmd instead of PS?

Used CMD and git Bash both, same error
![image](https://user-images.githubusercontent.com/82947413/187040344-214f7012-ef1b-44f1-8247-a448b6588fa6.png)

**Comment by ghost** [comment]
Is the user logged in?

**Comment by emlano** [comment]
> Is the user logined?

No, I have tried restarting the system and just logging into my main, have tried running mov-cli in that user account. mov-cli doesn't exist in that user. and the same error happens when I restart.

**Comment by ghost** [comment]
So i know why it won´t create a folder for mov-cli but why it uses a different user.

Is Python installed on that users account?

**Comment by ghost** [comment]
Test it i hope it works.

so reinstall it

**Comment by emlano** [comment]
> So i know why it won´t create a folder for mov-cli but why it uses a different user.
> 
> Is Python installed on that users account?

python is installed on both user accounts

**Comment by emlano** [comment]
> Test it i hope it works.
> 
> so reinstall it

I reinstalled it but it doesn't work, and gives out the same error, here's the installation log
![image](https://user-images.githubusercontent.com/82947413/187041653-f66da0a1-c18b-4312-9a08-5965efbabc6f.png)

**Comment by ghost** [comment]
Try Now.

**Comment by ghost** [comment]
So Reinstalling it again

**Comment by emlano** [comment]
> So Reinstalling it again

Works! Thank you very much!
