### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by Spaxly** [mov-cli/mov-cli#5]
An AUR package for this would greatly benefit Arch users.

**Comment by Poseidon444** [comment]
will be done soon

**Comment by SloppyPuppy** [comment]
Sure would, but its still kinda not ready for shipping, but I suppose adding it to AUR would get more people interested.

**Comment by 00ly** [comment]
I'm willing to maintain the AUR package. I think this is a good time to package it. If ready, I can start this asap.

**Comment by Poseidon444** [comment]
You can do it

**Comment by 00ly** [comment]
Great, getting started on it now. Will post a comment when finished.

**Comment by Comfort-Twala** [comment]
@00ly ... Just checking if there's any progress on that AUR package?

**Comment by ghost** [comment]
Looks like the AUR package was not released and no response from @00ly.
