### ISSUE TITLE
Feature: Options Menu

### ISSUE THREAD

**Issue by Seby877** [mov-cli/mov-cli#50]
Is it possible to make selected episodes "ex: select episode from 3 to 10" like ani-cli did in the last update.
I will do it myself but I'm a noob in scripts

**Comment by ghost** [comment]
What do you mean by select a episode. Like download a Season or what do you mean by that.

**Comment by Seby877** [comment]
I mean instead of pressing "N" and enter for next episode every time, you can just select 1 to 12 and autoplayed

**Comment by Seby877** [comment]
To specify a range, use: start_number end_number (Episodes: 1-1030)
This is the option for ani-cli, you can just choose 1 20 and watch 20 episodes

**Comment by Poseidon444** [comment]
This could be implemented and will soon be implemented

**Comment by THEGOLDENPRO** [comment]
V3 has been deprecated. The v4 issue for this can be tracked here --> #226
