### ISSUE TITLE
It's broken

### ISSUE THREAD

**Issue by Ao1Pointblank** [mov-cli/mov-cli#51]
using default provider (theflix):
```
The name of the provider [theflix]: 
[!] Sorry I don't know that provider! |  The read operation timed out
```

using Solar to select S3E1 of a tv show (the expanse):
```
[!] Sorry I don't know that provider! |  list index out of range
```

**Comment by CoLDHearT18** [comment]
I have the same issue as well, tried re-installing, still did not work.

**Comment by R3tr0Ananas** [comment]
What OS do you use?

**Comment by ghost** [comment]
TheFlix has Performance Issues and when you use Solar does it stop at www.google.com/recaptcha?

**Comment by CoLDHearT18** [comment]
Hi, I'm on windows 10, and as for the providers, I only use "sflix" and
"theflix" (the others are blocked in my country) both these providers are
showing the same error.

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/83706294/190461170-01a036b3-f1e0-4e01-af46-2e2938814c8b.png)

When trying does it look like that?

**Comment by CoLDHearT18** [comment]
yes exactly

**Comment by ghost** [comment]
Should be fixed by Tomorow.

Sry for the inconvenience.

**Comment by Ao1Pointblank** [comment]
no problem, and thank you for this software!

**Comment by CoLDHearT18** [comment]
Dude, you are doing this for free so don't apologize to anyone. I'm the one who's supposed to be thanking you for making this awesome client in the first place so Thank You!

**Comment by ghost** [comment]
i didn´t make this, @Poseidon444 did. 
I am just a Maintainer

**Comment by Poseidon444** [comment]
Was the issue fixed? or should I fix it?

**Comment by CoLDHearT18** [comment]
I just checked now, "theflix" works but "sflix" is still not working. The other providers are blocked in my country so I cant check. Also @Poseidon444 could you add atleast some of these providers to the client pls? 

1. [https://www1.f2movies.ru/](https://www1.f2movies.ru/)
2. [https://soap2day.sh/](https://soap2day.sh/) or [https://soap2day.mx/](https://soap2day.mx/)
3. [http://www.streamlord.com/](http://www.streamlord.com/)
4. [https://teatv.xyz/](https://teatv.xyz/)

**Comment by Poseidon444** [comment]
I'm currently fixing the problem, I will add the providers after exams, hopefully

**Comment by CoLDHearT18** [comment]
Alright Thanks and good luck :) @Poseidon444

**Comment by ghost** [comment]
Actvid and there relatives were updated on how they work, @Poseidon444 will fix Actvid and so on, i think i will add providers or work the Features list off.

**Comment by ghost** [comment]
So the current state is to rewrite everything...

It may take weeks or longer.

**Comment by CoLDHearT18** [comment]
oh damn, how big of an issue is this? well take your time and could you tag me here when you are done? @R3tr0Ananas

**Comment by ghost** [comment]
If i don´t forget it, i can.

**Comment by ttx99** [comment]
don't get me wrong, but I think you should disable the download feature of the script. I don't know much about coding but I think if they notice something out of the ordinary like downloads which is not what they are intended for. They will again and again change something on the server end. I mean there are torrents if you really want the file.    Just my opinion

**Comment by ghost** [comment]
They do not care, about downloads they just updated how they get the streaming link. if you go on the Actvid or its relatives sites, it gives you the option to download and torrents take too long.

**Comment by oubaycodes** [comment]
hey, has this issue been fixed? because i'm still getting the same error.

**Comment by ghost** [comment]
The Error was been fixed by @Poseidon444

**Comment by CoLDHearT18** [comment]
Dude, you are doing this for free so don't apologize to anyone. I'm the one
who's supposed to be thanking you for making this awesome client in the
first place so Thank You!
