### ISSUE TITLE
Is it broken again?

### ISSUE THREAD

**Issue by MrLDasVino** [mov-cli/mov-cli#53]
After the update it worked fine for a few hours but now I am once again unable to get past the "I don't know this provider"
So I am wondering if something broke on my end or did the sites change something again
![Screenshot 2022-09-28 161425](https://user-images.githubusercontent.com/57874812/192802923-e7eeffbe-d233-4982-86a4-adf20ac84a32.png)
I appreciate the work you guys have put into this thanks.

**Comment by SJTheGreat06** [comment]
I'm also facing same problem.

**Comment by Ao1Pointblank** [comment]
similar issues with ``theflix``
![image](https://user-images.githubusercontent.com/88149675/192905885-6b287de7-2371-42bc-9f2a-3957803b9a10.png)

**Comment by ghost** [comment]
theflix just vanished? 
![grafik](https://user-images.githubusercontent.com/83706294/193014326-175ddef0-1ece-42bf-baf5-51b0eb3b8990.png)

sflix works fine
![grafik](https://user-images.githubusercontent.com/83706294/193014397-bfb3bbef-90c0-4cdd-92c6-056672f8fdd9.png)

**Comment by ghost** [comment]
Which movie did you try to watch?

**Comment by MrLDasVino** [comment]
> Which movie did you try to watch?

I have tried a few different ones, with all the available providers, but that is very strange I tried it again just now and it appears to be working again

**Comment by MrLDasVino** [comment]
Must have been a temporary issue with the sites, sorry for any inconveniences caused
