### ISSUE TITLE
Some sort of "Encryption" issue

### ISSUE THREAD

**Issue by MrLDasVino** [mov-cli/mov-cli#55]
After the update it was again working fine for a while but now I am running into a new issue, it applies to all providers it just returns a "encrypted" error I will post a screenshot
![Screenshot 2022-10-03 175951](https://user-images.githubusercontent.com/57874812/193624170-7661eef7-90a1-424f-85cd-0fef43c572e5.png)
is this an issue on my end? thank you for your time

**Comment by ghost** [comment]
Did you try reinstalling it?

**Comment by MrLDasVino** [comment]
by using the pip install git+https://github.com/mov-cli/mov-cli command? yeah but I did not uninstall it prior

**Comment by ghost** [comment]
Then uninstall it and reinstall it.

**Comment by MrLDasVino** [comment]
I appreciate the help that seems to have fixed it, silly of me not to try uninstalling it first rather than trying to update it, Thank you for your help
