### ISSUE TITLE
Literally everything is broken

### ISSUE THREAD

**Issue by ohxxm** [mov-cli/mov-cli#61]
Nothing works, can't play anything, ends in errors. Used python version using `pip install mov-cli`

**Comment by MrLDasVino** [comment]
For me Eja does work but that is only for live tv channels of various countries, both theflix and vidsrc do not

**Comment by ghost** [comment]
i updated some things try "pip install mov-cli" again

**Comment by MrLDasVino** [comment]
Before the update vidsrc would find the searches but not load them, now it doesn't find searches either and just errors out, theflix does work but seems to only have a handful of movies, I have mostly used sflix which worked great for the most part but I suppose that one is no longer available

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/83706294/196452069-a7130977-7365-43cb-9fa9-5836ee55a9fe.png)
cant reproduce the bug that you have.

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/83706294/196452893-1b5b22cf-40b2-40bc-bfa1-da02b0c17587.png)
Maybe this is why theflix doesnt work

**Comment by ghost** [comment]
Well we discontinued sflix, actvid, dopebox, solar because they used an Hoster that try to block scrapers from getting .m3u8 file.

If you do want it you are free to fork it and fix the problem and do an pull request.

Sry for my broken english.

**Comment by ghost** [comment]
Try out the source of mov-cli.

**Comment by MrLDasVino** [comment]
> Well we discontinued sflix, actvid, dopebox, solar because they used an Hoster that try to block scrapers from getting .m3u8 file.
> 
> If you do want it you are free to fork it and fix the problem and do an pull request.
> 
> Sry for my broken english.

yeah that is understandable if they were being a pain, regardless thanks for all the work you have done

**Comment by ohxxm** [comment]
TheFlix is slow for whatever reason. Vidsrc still doesn't work as its error is `KeyError: 'qid'`.

**Comment by ghost** [comment]
> TheFlix is slow for whatever reason. Vidsrc still doesn't work as its error is `KeyError: 'qid'`.

I send a Screenshot where it says that theflix doing server upgrades, it isnt vidsrc specific it's imdb, the "qid" key says if its a movie or Show and on some it isnt there.

**Comment by ghost** [comment]
> TheFlix is slow for whatever reason. Vidsrc still doesn't work as its error is `KeyError: 'qid'`.

the "KeyError: "qid" error has been fixed

**Comment by ghost** [comment]
is there still any Issue or can this be closed?

**Comment by ohxxm** [comment]
Can be closed.
