### ISSUE TITLE
FZF

### ISSUE THREAD

**Issue by ohxxm** [mov-cli/mov-cli#62]
Would be cool to implement FZF instead of displaying plain text.

**Comment by ghost** [comment]
> Would be cool to implement FZF instead of displaying plain text.

I will look in to it, if i have some time.

**Comment by bachig26** [comment]
> I will look in to it, if i have some time.

@R3tr0Ananas  
https://github.com/justfoolingaround/fzf.py

I found this one from a similar cli app (https://github.com/DemonKingSwarn/flix-cli) that I use.

**Comment by ghost** [comment]
fzf has been added with the recent update.
