### ISSUE TITLE
unable to run mov-cli

### ISSUE THREAD

**Issue by toxicfox2491** [mov-cli/mov-cli#63]
in an arch linux vm I installed mov-cli and it just spits out line 1: not: command not found where as on my main pc (windows) it runs completely fine, no I didnt mix up the install cmds

**Comment by Poseidon444** [comment]
The python or the shell version?

**Comment by toxicfox2491** [comment]
> The python or the shell version?

python

**Comment by Poseidon444** [comment]
can you post the full error?

**Comment by toxicfox2491** [comment]
> can you post the full error?

ok so I had to re-install windows and I have to re setup VMware to get my arch setup running again but I did try installing it on windows and...
![weryhdefyte](https://user-images.githubusercontent.com/69102209/200046338-aae08cc3-63ba-43d3-b580-3fdf2d0ee05b.PNG)

**Comment by ghost** [comment]
Is the Scripts Folder from Python in the Path?

**Comment by toxicfox2491** [comment]
I was having some issues putting python in $PATH so I just went to the directory and ran pip install mov-cli and tried running it again

**Comment by Poseidon444** [comment]
pretty sure python needs to be in the path, however you can try using the shell version with gitbash

**Comment by toxicfox2491** [comment]
I cant do the gitbash one rn but I did try fixing my python install and it still cant install
I also did update pip and tried again but it didnt work
[output.txt](https://github.com/mov-cli/mov-cli/files/9993101/output.txt)

**Comment by ghost** [comment]
Oh i see you use Python Version 3.11 but lxml has only Version 3.10 precompiled. Just install Python 3.10 and it should be fixed

**Comment by Ao1Pointblank** [comment]
is there a new requirement to have a more recent version of python installed?

**Comment by ghost** [comment]
What do you mean?

**Comment by toxicfox2491** [comment]
ohh sorry lol I didnt notice it started using 3.11

**Comment by toxicfox2491** [comment]
smh dumb question but how do I use 3.10 over 3.11?

**Comment by toxicfox2491** [comment]
so normal installs of python dont work at all by the ones from the microsoft store do, dude wtf also the page for 3.10 freezes but all the other versions for python seem to be fine on the store WHY

**Comment by ghost** [comment]
Dont ever use the Store Versions.
Download python 3.10 from here https://www.python.org/downloads/release/python-3108

**Comment by toxicfox2491** [comment]
> Dont ever use the Store Versions. Download python 3.10 from here https://www.python.org/downloads/release/python-3108

thats the problem installing the builds from the site dont work at all and even trying to use python in the terminal will tell me to install the store version

**Comment by ghost** [comment]
dont use python3 in Terminal use python

**Comment by toxicfox2491** [comment]
> dont use python3 in Terminal use python

that opens the microsoft store

**Comment by Mihaau** [comment]
> that opens the microsoft store
Disable python app aliases in windows settings and restart cmd it should work.

**Comment by toxicfox2491** [comment]
> > that opens the microsoft store
> > Disable python app aliases in windows settings and restart cmd it should work.

tyvm
