### ISSUE TITLE
Unable to install mov-cli version 3.2

### ISSUE THREAD

**Issue by MrLDasVino** [mov-cli/mov-cli#64]
I have tried to do a fresh install but every time it just installs the previous version
![Screenshot 2022-11-05 025705](https://user-images.githubusercontent.com/57874812/200096063-022bd242-fc1b-4260-91c5-790f084b86b1.png)
is there something specific I need to do?

**Comment by ghost** [comment]
You are trying to install the source or the PyPi Version?

**Comment by MrLDasVino** [comment]
I imagine its the source version, I am using the pip install mov-cli command to install has worked fine so far except for this last update

**Comment by ghost** [comment]
> I imagine its the source version, I am using the pip install mov-cli command to install has worked fine so far except for this last update

Nothings wrong i just forgot to update the pypi version.

Sorry.

**Comment by ghost** [comment]
I will update it after i add Subtitles Function.

**Comment by MrLDasVino** [comment]
thanks I appreciate it, I suppose that solves this issue then, hope you have a wonderful day

**Comment by ghost** [comment]
PyPi Version has been updated.
