### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli#66]
I remember trying mov-cli on my phone a long time ago but it never worked so I assumed there wasn't support.

So is there currently android support for mov-cli?

**Comment by ghost** [comment]
We didn't implement android support, i would test it my self but i don't use an Android Device. Just try out for yourself.

**Comment by THEGOLDENPRO** [comment]
> We didn't implement android support, i would test it my self but i don't use an Android Device. Just try out for yourself.

Yeah I'll look into it and perhaps even perform a pull request if I get it working. :)

**Comment by THEGOLDENPRO** [comment]
Okay I got it working so far on Android with Termux but I still got a few things I got to fix until it's ready.

**Comment by Poseidon444** [comment]
alright, looking forward to it

**Comment by THEGOLDENPRO** [comment]
Damn it's been two weeks I've almost forgotten about this.

Anyways I was working on it and I did manage to get it to work but I only could get it to work on every other provider except the default provider. The default provider will only work if its referer URL is entered in the mpv.config.

The issue with MPV on Android is that you cannot pass through a referer URL when playing media, so the user will have to manually enter this in the config. The issue with this is that you can only have one referrer URL in there so for example the user wouldn't be able to use ani-cli after adding our referrer URL. I find it really annoying having to switch between the two.

So I think we have a few options wit Android playback:

1) Just assume the user doesn't use any other android mpv cli tool like ani-cli.

2) Change to a new default provider that does work on Android without referrer URL.

3) Disallow the current default provider and warn the user if they are using it on Android.

Idk how you would like to go about things here. 

When I get home I'll push my current changes to my fork and link it here.

**Comment by THEGOLDENPRO** [comment]
> When I get home I'll push my current changes to my fork and link it here.

https://github.com/THEGOLDENPRO/mov-cli/tree/android-support

**Comment by THEGOLDENPRO** [comment]
> > When I get home I'll push my current changes to my fork and link it here.
> 
> https://github.com/THEGOLDENPRO/mov-cli/tree/android-support

this is my current progress but note the custom config solution I was trying to implement is not going to work, I'll have to remove that soon.

**Comment by Poseidon444** [comment]
i'll think about the default provider

**Comment by Poseidon444** [comment]
i've gone through the commit, it should work

**Comment by Seby877** [comment]
Why do I get this error, ani-cli works fine.



mov-cli
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mov-cli", line 33, in <module>
    sys.exit(load_entry_point('mov-cli==0.4.6', 'console_scripts', 'mov-cli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/bin/mov-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/__init__.py", line 1, in <module>
    from . import __main__
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/__main__.py", line 36, in <module>
    startup.getkey()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/onstartup.py", line 31, in getkey
    with open(f"{startup.winorlinux()}/movclikey.txt", "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/u0_a1155/movclikey.txt'

**Comment by THEGOLDENPRO** [comment]
> Why do I get this error, ani-cli works fine.
> 
> 
> 
> mov-cli
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/usr/bin/mov-cli", line 33, in <module>
>     sys.exit(load_entry_point('mov-cli==0.4.6', 'console_scripts', 'mov-cli')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/bin/mov-cli", line 25, in importlib_load_entry_point
>     return next(matches).load()
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
>     module = import_module(match.group('module'))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/__init__.py", line 1, in <module>
>     from . import __main__
>   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/__main__.py", line 36, in <module>
>     startup.getkey()
>   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/onstartup.py", line 31, in getkey
>     with open(f"{startup.winorlinux()}/movclikey.txt", "w") as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: '/home/u0_a1155/movclikey.txt'

Werid. Is this my fork of mov-cli, the original repo doesn't support Android yet.

**Comment by THEGOLDENPRO** [comment]
But also I have not seen that error before.

**Comment by ghost** [comment]
> > Why do I get this error, ani-cli works fine.
> > mov-cli
> > Traceback (most recent call last):
> > File "/data/data/com.termux/files/usr/bin/mov-cli", line 33, in 
> > sys.exit(load_entry_point('mov-cli==0.4.6', 'console_scripts', 'mov-cli')())
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/data/data/com.termux/files/usr/bin/mov-cli", line 25, in importlib_load_entry_point
> > return next(matches).load()
> > ^^^^^^^^^^^^^^^^^^^^
> > File "/data/data/com.termux/files/usr/lib/python3.11/importlib/metadata/**init**.py", line 198, in load
> > module = import_module(match.group('module'))
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/data/data/com.termux/files/usr/lib/python3.11/importlib/**init**.py", line 126, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "", line 1206, in _gcd_import
> > File "", line 1178, in _find_and_load
> > File "", line 1128, in _find_and_load_unlocked
> > File "", line 241, in _call_with_frames_removed
> > File "", line 1206, in _gcd_import
> > File "", line 1178, in _find_and_load
> > File "", line 1149, in _find_and_load_unlocked
> > File "", line 690, in _load_unlocked
> > File "", line 940, in exec_module
> > File "", line 241, in _call_with_frames_removed
> > File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/**init**.py", line 1, in 
> > from . import **main**
> > File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/**main**.py", line 36, in 
> > startup.getkey()
> > File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/onstartup.py", line 31, in getkey
> > with open(f"{startup.winorlinux()}/movclikey.txt", "w") as f:
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/u0_a1155/movclikey.txt'
> 
> Werid. Is this my fork of mov-cli, the original repo doesn't support Android yet.

It's the normal version of mov-cli, your Fork isn't updated to latest update. Your fork still makes an request to github api when using actvid, but the latest gets it on start up and uses it for actvid.

if you update the fork just put the movclikey.txt to /data/data/com.termux/files/home

Excuse my lack of English.

**Comment by THEGOLDENPRO** [comment]
> > > Why do I get this error, ani-cli works fine.
> > > mov-cli
> > > Traceback (most recent call last):
> > > File "/data/data/com.termux/files/usr/bin/mov-cli", line 33, in
> > > sys.exit(load_entry_point('mov-cli==0.4.6', 'console_scripts', 'mov-cli')())
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > File "/data/data/com.termux/files/usr/bin/mov-cli", line 25, in importlib_load_entry_point
> > > return next(matches).load()
> > > ^^^^^^^^^^^^^^^^^^^^
> > > File "/data/data/com.termux/files/usr/lib/python3.11/importlib/metadata/**init**.py", line 198, in load
> > > module = import_module(match.group('module'))
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > File "/data/data/com.termux/files/usr/lib/python3.11/importlib/**init**.py", line 126, in import_module
> > > return _bootstrap._gcd_import(name[level:], package, level)
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > File "", line 1206, in _gcd_import
> > > File "", line 1178, in _find_and_load
> > > File "", line 1128, in _find_and_load_unlocked
> > > File "", line 241, in _call_with_frames_removed
> > > File "", line 1206, in _gcd_import
> > > File "", line 1178, in _find_and_load
> > > File "", line 1149, in _find_and_load_unlocked
> > > File "", line 690, in _load_unlocked
> > > File "", line 940, in exec_module
> > > File "", line 241, in _call_with_frames_removed
> > > File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/**init**.py", line 1, in
> > > from . import **main**
> > > File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/**main**.py", line 36, in
> > > startup.getkey()
> > > File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/onstartup.py", line 31, in getkey
> > > with open(f"{startup.winorlinux()}/movclikey.txt", "w") as f:
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > FileNotFoundError: [Errno 2] No such file or directory: '/home/u0_a1155/movclikey.txt'
> > 
> > 
> > Werid. Is this my fork of mov-cli, the original repo doesn't support Android yet.
> 
> It's the normal version of mov-cli, your Fork isn't updated to latest update. Your fork still makes an request to github api when using actvid, but the latest gets it on start up and uses it for actvid.
> 
> Excuse my lack of English.

Ah okay thanks for clearing that up, I was a bit confused when I saw `/onstartup.py`.

**Comment by THEGOLDENPRO** [comment]
okay yeah after pulling from upstream I'm getting this same error on android. I'm gonna fix that in my fork.

**Comment by THEGOLDENPRO** [comment]
> okay yeah after pulling from upstream I'm getting this same error on android. I'm gonna fix that in my fork.

fixed in https://github.com/THEGOLDENPRO/mov-cli/commit/a7f0dbffb1d699f7e64255ae61dc1bbf0f9e477e

**Comment by THEGOLDENPRO** [comment]
okay so all the providers seem to work without changing the referrer in MPV player except `theflix`

**Comment by THEGOLDENPRO** [comment]
> okay so all the providers seem to work without changing the referrer in MPV player except `theflix`

so we might have to set a different provider as recommended for android

**Comment by THEGOLDENPRO** [comment]
Also if someone else with an Android could test this out that would be perfect. My first time working with anything on android.
