### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by BloodZero0** [mov-cli/mov-cli#69]
Every time the program tries to do a search, this error pops out: 
`[!] An error has occurred |  Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`

I found out this error pops out because of the lines: 
`soup = BS(source, "lxml")`
should be:
`soup = BS(source, "html.parser")`

IDK if this is an error of the lxml library or if the new python version made some breaking changes, anyway using html.parser solves the problem, so I'm going to fix all the lines and make a pull request

**Comment by ghost** [comment]
You do know you can install lxml with pip install lxml

**Comment by BloodZero0** [comment]
> You do know you can install lxml with pip install lxml

Yeah, but the error is still present. I'll send you some screenshots: 
https://ibb.co/Dt8T7JX
https://ibb.co/bJXJ4tS

I also tried updating lxml and reinstalling lxml, no luck so far.

**Comment by ghost** [comment]
Do you maybe have two Python Version installed?

**Comment by BloodZero0** [comment]
> Do you maybe have two Python Version installed?

Nope, only python 3.11.0 is installed.

**Comment by ghost** [comment]
Try Python 3.10

**Comment by BloodZero0** [comment]
ok, on python 3.10 works flawlessly.

**Comment by ghost** [comment]
So this can be closed?

**Comment by BloodZero0** [comment]
yes, thanks for your help.
