### ISSUE TITLE
"The Current Provider has changed"

### ISSUE THREAD

**Issue by Ao1Pointblank** [mov-cli/mov-cli#73]
Certain providers cannot load content, only showing this message before the program quits:
"The Current Provider has changed"
this is the Python version of mov-cli.

Perhaps related, theflix doesn't load content either. instead, it sends the user in a loop of "Enter your choice" (in my system monitor, i can see mpv tries to launch, then quits after a few seconds without showing the player window)

**Comment by ghost** [comment]
Which Providers do you mean with Certain?

Yeah theflix is kinda broke

**Comment by MrLDasVino** [comment]
Seems like most of them are giving this error, I imagine its the ones that share the same provider cluster

**Comment by Poseidon444** [comment]
I can confirm this, actvid and it's associates are broken, this will be fixed in due time

**Comment by ghost** [comment]
It has been fixed
