### ISSUE TITLE
Can not download ('utf-8' codec error

### ISSUE THREAD

**Issue by JonU238** [mov-cli/mov-cli#75]

**Comment by JonU238** [comment]
When I try to download a movie it prints the url's to the screen and then throws the error:
[ ! ] Invalid Choice Entered! | 'utf-8' codex can't decode byte 0x91 in position 0: invalid start byte
![2022-11-28-173841_720x576_scrot](https://user-images.githubusercontent.com/59961512/204433575-24b901dd-1e75-468f-91d3-82bdad936b77.png)

**Comment by Poseidon444** [comment]
Actvid and it's associates are currently broken, we're trying to fix them

**Comment by JonU238** [comment]
Ok, thank you!
