### ISSUE TITLE
[!] An error has occurred |  'movie'

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#76]
When I try to use theflix, I get this error:
```
[!] An error has occurred |  'movie'
```

**Comment by Poseidon444** [comment]
Trying updating the package, if the issue persists please provide some details like average internet speed.

**Comment by MrLDasVino** [comment]
Theflix works on my end, in my experience when it just spits out the "movie" error it doesnt have the movie in the server despite showing it as a search

**Comment by ghost** [comment]
Problem has been explained by [MrLDasVino](https://github.com/MrLDasVino)

**Comment by umop3plsdn** [comment]
wait theflix works for you guys? i always get 
The name of the provider [theflix]:
[!] An error has occurred |  The read operation timed out

**Comment by ghost** [comment]
Well thats because TheFlix is god damn slow for some reason
