### ISSUE TITLE
add support for asian providers

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#78]
#### Asian providers (from CS Extension Repo)

1. https://github.com/hexated/cloudstream-extensions-hexated
2. https://github.com/recloudstream/cloudstream-extensions-multilingual
3. https://github.com/consumet/consumet.ts/tree/master/src/providers/movies

#### Indian providers (from CS Extension Repo)

1. https://github.com/daarkdemon/cs-darkdemon-extensions
2. https://github.com/LikDev-256/likdev256-tamil-providers

#### Some of the Asian providers (possible present in the repos above) 

1. https://watchasian.la/
2. https://viewasian.co/
3. https://asianembed.io/
4. http://kshow123.net/
5. https://mxdrama.com/
6. https://einthusan.tv/
7. https://streamblasters.art/
8. https://kisskh.me/
9. https://fdrama.net/
10. https://www.newhkdrama.com/

**Comment by bachig26** [comment]
@R3tr0Ananas @Poseidon444 can you guys look into the possibility of adding Asian providers to the cli?

**Comment by ghost** [comment]
Yeah, i am currently trying to add [viewasian.co](https://viewasian.co/)

**Comment by bachig26** [comment]
> Yeah, i am currently trying to add [viewasian.co](https://viewasian.co/)

Glad to hear that. Thank you so much.

**Comment by ghost** [comment]
[viewasian.co](https://viewasian.co/) has been added. 
![grafik](https://user-images.githubusercontent.com/83706294/211618538-5ef59b5f-9c32-4970-b337-a26568968436.png)

**Comment by bachig26** [comment]
> [viewasian.co](https://viewasian.co/) has been added.

@R3tr0Ananas can you able add support for doodstream server/extractor instead or in addition to the xstreamcdn, because from my use dood is the reliable and doesn't have much buffer compared to xstreamcdn. for me, xstreamcdn caches like 2-10 seconds and stops for few seconds and again caches 2-5 seconds and it stays like this for every video that I have tried.

**Comment by ghost** [comment]
So DoodStream is not usable because yt-dlp or in mpv ytdl_hook stops it.
![grafik](https://user-images.githubusercontent.com/83706294/211645424-a90c9679-8429-41a1-8cba-c86d034c64a8.png)
I can add Streamtape but it's not used on every show

**Comment by bachig26** [comment]
> So DoodStream is not usable because yt-dlp or in mpv ytdl_hook stops it.
> 
> ![grafik](https://user-images.githubusercontent.com/83706294/211645424-a90c9679-8429-41a1-8cba-c86d034c64a8.png)
> 
> I can add Streamtape but it's not used on every show
> 
> 

Oh okay 👍

**Comment by ghost** [comment]
So i couldn't add Streamtape they have Secured there Site pretty well because last time it was very easy but now and every time i some dude just saying: YOU TRYED USING STREAMTAPE WITH A 3RD PART SERVICE.

**Comment by ghost** [comment]
So i added streamtape after having an mental break down on why it won't work.

**Comment by bachig26** [comment]
> So i added streamtape after having an mental break down on why it won't work.

what happened?

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/83706294/212113309-e6d2443a-0236-4818-bb89-9e009087ac4e.mp4

this happened.

**Comment by bachig26** [comment]
> 
> 
> https://user-images.githubusercontent.com/83706294/212113309-e6d2443a-0236-4818-bb89-9e009087ac4e.mp4
> 
> 
> 
> this happened.

maybe this is related to the token or encryption key.

**Comment by ghost** [comment]
i don't know but streamtape is added sooo

**Comment by bachig26** [comment]
@R3tr0Ananas the video plays on both doodstream and streamtape, but I'm seeing an line in the terminal `name 'dc' is not defined` which I don't know what it is.

````
 mov-cli
[X]: Error while connecting to Discord


Movies and Shows:
theflix
actvid
sflix
solar
dopebox
viewasian

Anime:
gogoanime

Live TV:
eja
ustvgo / US IP ONLY

Cartoons:
kimcartoon

The name of the provider [theflix]: viewasian
None
[!] Please Enter the name of the Movie: meet yourself
https://viewasian.co/movie/search/meet-yourself
[1] Meet Yourself (2023) TV

[2] Meet Yourself (2023) TV

[q] Exit!

[s] Search Again!

[d] Download!

[p] Switch Provider!

[sd] Download Whole Show!

Enter your choice: 1
https://viewasian.co/drama/meet-yourself
https://viewasian.co/watch/meet-yourself/watching.html
Please input the episode number(Total: 18): 18
https://viewasian.co/watch/meet-yourself/watching.html?ep=18
What Streaming Service do you want:
[1] DoodStream
[2] StreamTape
Please Enter what you want to use: 1
https://dood.wf/e/0i96odr83l8a
https://dood.wf/pass_md5/82341213-79-230-1673557187-af2e32322bf3cb8375afc8c036338f3e/eybbad73ji8mq93qh8mdq7k1
https://ll288op.dood.video/u5kj6iad4dflsdgge5isgzq7chb5dxcbbfvls3wbn4dr3agglt6wbtkcaona/9h50b7vim5~zUEJeL3mUN?token=eybbad73ji8mq93qh8mdq7k1
https://ll288op.dood.video/u5kj6iad4dflsdgge5isgzq7chb5dxcbbfvls3wbn4dr3agglt6wbtkcaona/9h50b7vim5~zUEJeL3mUN?token=eybbad73ji8mq93qh8mdq7k1
name 'dc' is not defined
Enter your choice: 1
https://viewasian.co/drama/meet-yourself
https://viewasian.co/watch/meet-yourself/watching.html
Please input the episode number(Total: 18): 18
https://viewasian.co/watch/meet-yourself/watching.html?ep=18
What Streaming Service do you want:
[1] DoodStream
[2] StreamTape
Please Enter what you want to use: 2
https://streamtape.com/e/k99vGXme24iOzkk
https://streamtape.com/get_video?id=k99vGXme24iOzkk&expires=1673627220&ip=GHysDRORKxSHDN&token=LQJNCO469-V4
name 'dc' is not defined
````

**Comment by ghost** [comment]
yeah i removed the discord rpc should be fixed now and watchasian was added. 👍

**Comment by ghost** [comment]
That should be enough asian providers for the timebeing,
