### ISSUE TITLE
[FEATURE] Add support for subtitles.

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#79]
I have seen the subtitles are available in most the providers via the settings option in the video player but the mov-cli doesn't extract them.

will it be supported? or possible external support to be included like subscene or others?

**Comment by diniamo** [comment]
Are there any plans to implement this? Can you tell me how you use DevTools on the provider websites so I can give it a shot? They seem to have some kind of mechanism to prevent it, and I couldn't find any working workarounds on google.

**Comment by shinysocks** [comment]
[subliminal](https://github.com/Diaoul/subliminal)

**Comment by bachig26** [comment]
if subtitles are planned in future, and if it's going to be external by downloading from subscene or opensubtitles. i think caching the subtitle files and automatically deleted after the mpv is closed would be a nice addition.

**Comment by bachig26** [comment]
in case of multiple subtitle support, i like this idea from clistream (https://github.com/Thanatoslayer6/clistream) which uses NodeJS but idea is nice,. it streams from sflix and fetches every subtitles they provided in their site video player and we can select the all or needed languages in cli and switch between them in mpv as usual.

**Comment by shinysocks** [comment]
I'm going to try an implementation using subliminal and see how consistent it is.. if I have any free time

**Comment by shinysocks** [comment]
> I'm going to try an implementation using subliminal and see how consistent it is.. if I have any free time

subliminal seems to be losing maintainers so I might look into alternatives, let me know anyone knows of stable python libraries for subs

**Comment by THEGOLDENPRO** [comment]
I'm removing the V3 label, I think this issue can be looked into for V4.

**Comment by shinysocks** [comment]
attempting to implement into v4

**Comment by shinysocks** [comment]
[this](https://opensubtitles.stoplight.io/docs/opensubtitles-api) is currently the API i'm trying to use but I'm encountering troubles.. does anyone know of good simple subtitle libraries for python?

**Comment by shinysocks** [comment]
once we've got a good provider the rest shouldn't be too bad to set up

**Comment by THEGOLDENPRO** [comment]
Sadly I am not aware of any subtitle services. @r3tr0ananas are you?

**Comment by ananasmoe** [comment]
> Sadly I am not aware of any subtitle services. @r3tr0ananas are you?

I am also not aware of any subtitle services.

**Comment by EbanNox** [comment]
> Sadly I am not aware of any subtitle services. @r3tr0ananas are you?

Opensubs is a good one 👍,  a very easy and well made api that should be easy to incorporate in to a plugin, and the api key is easy and free to obtain. But my recommendation is to implement t this in a plugin so that every api key is obtained by each user who whants to use this plugin. And make this plugin to provide additional "- --" argument options for mov-cli to make things easier.

**Comment by THEGOLDENPRO** [comment]
> But my recommendation is to implement t this in a plugin so that every api key is obtained by each user who whants to use this plugin.

Since it's just subtitles I wouldn't mind incorporating this into mov-cli natively. I don't think a plugin would work well.

On that topic, I'm currently brainstorming how subtitles would be implemented in a sane manner. I don't know how these subtitles APIs work so I can't think about implementation well. 

What do you have to send to these APIs to get subtitles?

**Comment by THEGOLDENPRO** [comment]
> [subliminal](https://github.com/Diaoul/subliminal)

If that works well we can use it. If it's not in a bad state and I can wrap my head around it's codebase I may even contribute to the project.

In the meantime, I've been looking into [subscene](https://subscene.com). They seem to be pretty good and I don't think they have a daily download limit (correct me if I'm wrong). We can have an API for it in mov-cli allowing scrapers to take advantage of it.

Also, I don't know much about subtitles but a lot of these subtitles I've been trying from both [open subtitles](https://www.opensubtitles.com/) and subscene have been either wrong or lagging behind or too ahead of the actual media.

**Comment by THEGOLDENPRO** [comment]
I tried [subliminal](https://github.com/Diaoul/subliminal) and I didn't have any luck. It seems to be erroring internally without giving me a traceback so debugging is difficult.

At this point, I rather build a subtitles python lib myself lmao.

**Comment by shinysocks** [comment]
check this out^

**Comment by shinysocks** [comment]
i just need help integrating
