### ISSUE TITLE
RIP 9goal

### ISSUE THREAD

**Issue by pitsi** [mov-cli/mov-cli#81]
In case you missed the news, 9goal and a bunch of other sites were closed down (seized by HSI actually) a couple of days ago.
Their webpage is unavailable and so is their api used by mov-cli, with cloudflare returning a 521 error for both (checked with various ips from around the world with nordvpn). Thus, 9goal can now be removed from mov-cli :(

And all this happened right when I wanted to start using the python version of mov-cli because of 9goal!

**Comment by Poseidon444** [comment]
we'll look for an alternative!

**Comment by Seby877** [comment]
www.rofootball.com alternative if is possible, has most of the important sport channels from uk ,us, spain etc no restriction, i haven't tested all of them but most of them are working and also have alternative links if first doesn't work (but not sure  if that a issue ).

**Comment by pitsi** [comment]
9goal was removed completely 2 days ago, with commit c7d8b4e, so I am closing this.
I hope a new sports provider will be found.
