### ISSUE TITLE
not working `The Current Provider has changed`

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#82]
I've tried the provided `sflix` and `dopebox` are working as it shows that the provider has changed. 

also playing contetns via `theflix` crashes when skipping through in the progress bar.

@R3tr0Ananas please have look into this issue. Thank you.

**Comment by ghost** [comment]
So Sflix and dopebox works just fine.

The Issue with TheFlix has to do with TheFlix it self.

**Comment by ghost** [comment]
This should work normal too
