### ISSUE TITLE
Adding Providers

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#87]
If you want a Provider to be added just comment under this issue.

The provider can be in any language.

**Comment by bachig26** [comment]
Turkish TV Series site: Turkish123 (https://turkish123.com/)

for reference:
1. Cloudstream Hexated Repo: https://github.com/hexated/cloudstream-extensions-hexated/blob/master/Turkish/src/main/kotlin/com/hexated/Turkish.kt
2. Turkish123 Downloader: https://github.com/anburocky3/turkish123-downloader
3. Ketsu Module Parser: https://github.com/Bilnaa/bilnaa.github.io/tree/main/Turkish123 | Resolver: https://github.com/Bilnaa/bilnaa.github.io/tree/main/resolvers/ketsu

this is an alternate site that I use: 
- YoTurkish (https://www.yoturkish.com/)

**Comment by bachig26** [comment]
[WLEXT](https://wlext.is/) has been added

**Comment by bachig26** [comment]
https://github.com/edl2/sportsapi

A Python based API which has about 15+ providers or sites for streaming sports TVs.

**Comment by bachig26** [comment]
### Indian Providers (Movies, Web Series, TV Shows) _(these are set of providers that I use and some are new, I have arranged based on my preference of use)_


1. [StreamBlasters](https://streamblasters.art/) added
2. [Einthusan](https://einthusan.tv/), [reference](https://github.com/LikDev-256/likdev256-tamil-providers/tree/master/EinthusanProvider/src/main/kotlin/com/likdev256) from cloudstream LikDev-256 repo
3. [MovieHUB](https://x265rips.us/), [reference](https://github.com/LikDev-256/likdev256-tamil-providers/tree/master/MovieHUBProvider/src/main/kotlin/com/likdev256) from cloudstream LikDev-256 repo
4. [Bolly2Tolly](https://www.bolly2tolly.net/), [reference](https://github.com/daarkdemon/cs-darkdemon-extensions/tree/master/Bolly2TollyProvider/src/main/kotlin/com/darkdemon) from cloudstream Darkdemon repo
5. [ShowFlix](https://showflix.click/), [reference](https://github.com/LikDev-256/likdev256-tamil-providers/tree/master/ShowFlixProvider/src/main/kotlin/com/likdev256) from cloudstream LikDev-256 repo
6. [TamilYogi](https://tamilyogi.love/) added
7. [Movierulzhd](https://movierulzhd.store/), [reference](https://github.com/hexated/cloudstream-extensions-hexated/tree/master/Movierulzhd/src/main/kotlin/com/hexated) from cloudstream hexated repo
8. [Cinevez](https://ww2.cinevez.mx/), [reference](https://github.com/daarkdemon/cs-darkdemon-extensions/tree/master/CinevezProvider/src/main/kotlin/com/darkdemon) from cloudstream Darkdemon repo
9. [HDMovie](https://hdmovie2.ac/), [reference](https://github.com/recloudstream/cloudstream-extensions-multilingual/tree/master/HDMovie5/src/main/kotlin/com/lagradost) from cloudstream Non-English repo

**_*Note: Providers no. 1, 2, 4 (my frequents) has vast contents on Indian contents; Providers no. 3, 5 has only HD Quality contents no CAM copy. Rest of the 4 providers are backup._**


please have a look at these.

**Comment by bachig26** [comment]
I can suggest these API which has providers scraped and this can be used to add more providers.

- Consumet: https://github.com/consumet
- Kamyroll: https://github.com/kamyroll/Kamyroll-Wiki

Consumet is an API to watch movies, TV shows, Anime and read Manga. Consumet currently supports the providers like [flixhq](https://flixhq.to), [dramacool](https://dramacool.cr), [viewasian](https://viewasian.co), [Ummangurau](https://www1.ummagurau.com), [Zoro](https://zoro.to), [Gogoanime](https://www.gogoanime.dk), [Kamyroll](https://api.kamyroll.tech), [Crunchyroll](https://cronchy.consumet.stream/), [Enime](https://enime.moe), [AnimeFox](https://animefox.tv), [AnimePahe](https://animepahe.com), [Bilibili](https://bilibili.tv), [9Anime](https://9anime.pl), [KickAssAnime](https://www2.kickassanime.ro). 
In here, Cruncyroll is made by Consumet team and mentioned that the content reflects to user location based contents, not like Kamyroll. 9Anime doesn't work, as it hasn't been fixed.
Consumet API Documentation isn't complete yet, and a developer is correctly working on them, but still can be implemented.

Kamyroll is an API for Cruncyroll with US server, which can make the contents restricted to US based contents only.

@R3tr0Ananas you try looking into these which can expand the providers list to the mov-cli app.

**Comment by bachig26** [comment]
<details> @R3tr0Ananas I just saw that you have added hentai as a provider, so with that in mind I'm asking for the possibility to include JAV. This request can be ignored by you if you don't want.

Few Recommendations:
- [JAVCT](https://javct.net/)
- [SEXTB](https://sextb.net/)
- ~~[ROSHY.TV](https://roshy.tv/)~~ _some missing_
</details>

**Comment by ghost** [comment]
> @R3tr0Ananas I just saw that you have added hentai as a provider, so with that in mind I'm asking for the possibility to include JAV. This request can be ignored by you if you don't want.
> 
> Few Recommendations:
> 
>     * [JAVCT](https://javct.net/)
> 
>     * [SEXTB](https://sextb.net/)
> 
>     * ~[ROSHY.TV](https://roshy.tv/)~ _some missing_

i add JAVCT but hows your adventure with learning how to scrape?

**Comment by bachig26** [comment]
> hows your adventure with learning how to scrape?

I haven't learning on everyday and I jump between html (for div and such) and python, also referring some of your scrapes here in the app as example.
still having some doubts on some but learning little by little.

**Comment by Poseidon444** [comment]
How about a age verification or something, if there are providers for mature content?

**Comment by bachig26** [comment]
@R3tr0Ananas @Poseidon444 is there any plan for Discord server or something like that?

**Comment by ghost** [comment]
> How about a age verification or something, if there are providers for mature content?

i guess you mean like ask the user really wants to use this provider?

**Comment by ghost** [comment]
> @R3tr0Ananas @Poseidon444 is there any plan for Discord server or something like that?

Ask @Poseidon444 about that as he is created the project.

**Comment by Poseidon444** [comment]
> 

yea ,ig

**Comment by ghost** [comment]
> @R3tr0Ananas I just saw that you have added hentai as a provider, so with that in mind I'm asking for the possibility to include JAV. This request can be ignored by you if you don't want.

So for some reason javct makes some titles short and some with entre description but i think "it's good enough".

**Comment by R3tr0Ananas** [comment]
@bachig26 do you have some English, Russian, German or any different languaged sites to add as the indian and wlext has been added.

**Comment by ghost** [comment]
> Turkish TV Series site: Turkish123 (https://turkish123.com/)
> 
> for reference:
> 
>     1. Cloudstream Hexated Repo: https://github.com/hexated/cloudstream-extensions-hexated/blob/master/Turkish/src/main/kotlin/com/hexated/Turkish.kt
> 
>     2. Turkish123 Downloader: https://github.com/anburocky3/turkish123-downloader
> 
>     3. Ketsu Module Parser: https://github.com/Bilnaa/bilnaa.github.io/tree/main/Turkish123 | Resolver: https://github.com/Bilnaa/bilnaa.github.io/tree/main/resolvers/ketsu
> 
> 
> this is an alternate site that I use:
> 
>     * YoTurkish (https://www.yoturkish.com/)

Do you use Option 1 so (https://tukipasti.com) or Option 2 (https://lajkema.com) more?

**Comment by bachig26** [comment]
> Do you use Option 1 so (https://tukipasti.com) or Option 2 (https://lajkema.com) more?

I mainly use Option 1 (https://tukipasti.com) which doesn't buffer for me. Option 2 (https://lajkema.com) takes too long to load and has buffer issue, also ping isn't good for Option 2.

**Comment by ghost** [comment]
> > Do you use Option 1 so (https://tukipasti.com) or Option 2 (https://lajkema.com) more?
> 
> I mainly use Option 1 (https://tukipasti.com) which doesn't buffer for me. Option 2 (https://lajkema.com) takes too long to load and has buffer issue, also ping isn't good for Option 2.

Turkish123 was added
