### ISSUE TITLE
[Bug] watchasian fetching same dood link

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#88]
@R3tr0Ananas as you can see below the episodes are different but the dood links which fetched are same and playing same content.

````
The name of the provider [theflix]: watchasian
None
[!] Please Enter the name of the Movie: meet yourself
https://watchasian.la/search?type=movies&keyword=meet+yourself
[1] Meet Yourself (2023) TV

[q] Exit!

[s] Search Again!

[d] Download!

[p] Switch Provider!

[sd] Download Whole Show!

Enter your choice: 1
https://watchasian.la/drama-detail/meet-yourself
Please input the episode number(Total: 20): 18
https://watchasian.la/meet-yourself-2023-episode-18.html
https://dood.wf/e/0i96odr83l8a
https://dood.wf/pass_md5/82341213-79-230-1673576957-c8ac04178a2402ed2070b5f1e36fb765/eybbad73ji8mq93qh8mdq7k1
https://ll288op.dood.video/u5kj6iad4dflsdgge5isgzq7chb5dxcbbfvls3wbn4dr3agglt6v2gsdaona/2ct41aaw8n~zUEJeL3mUN?token=eybbad73ji8mq93qh8mdq7k1
Enter your choice: 1
https://watchasian.la/drama-detail/meet-yourself
Please input the episode number(Total: 20): 19
https://watchasian.la/meet-yourself-2023-episode-19.html
https://dood.wf/e/1ktfz83hwxg1
https://dood.wf/pass_md5/82341213-79-230-1673576957-c8ac04178a2402ed2070b5f1e36fb765/eybbad73ji8mq93qh8mdq7k1
https://ll288op.dood.video/u5kj6iad4dflsdgge5isgzq7chb5dxcbbfvls3wbn4dr3agglt6qmg2daona/g9qlxm9cre~zUEJeL3mUN?token=eybbad73ji8mq93qh8mdq7k1
````

**Comment by bachig26** [comment]
I have checked with the browser, which plays the correct content with dood.

**Comment by ghost** [comment]
Is it only on WatchAsian?

**Comment by ghost** [comment]
And Check if the contents are different on dood

**Comment by bachig26** [comment]
@R3tr0Ananas this issue is also present in viewasian, just checked.

and the contents are played correctly (contents are different for the both episodes) via the web browser.

**Comment by ghost** [comment]
I'll fix it later bc it's 3 am where i live so

**Comment by bachig26** [comment]
> I'll fix it later bc it's 3 am where i live so

yes, I know...here too..
sorry.

**Comment by ghost** [comment]
> > I'll fix it later bc it's 3 am where i live so
> 
> 
> 
> yes, I know...here too..
> 
> sorry.

It's okay 👍

**Comment by ghost** [comment]
Was it after i added the extractors.py or was it already so?

**Comment by ghost** [comment]
should be fixed

**Comment by bachig26** [comment]
> Was it after i added the extractors.py or was it already so?

i think it's in the latest version 0.5.6, 
I'll try the new version and let you know.

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/83706294/212228768-83ca4ba3-b6fc-4ae5-a51d-89284bae1cec.png)

has been fixed

**Comment by bachig26** [comment]
it's good now. 👍

**Comment by ghost** [comment]
i just shouldn't touch anything that already works xD.

**Comment by ghost** [comment]
Ich sehe gerade erst das du aus Deutschland kommst, falls du deutsche streaming seiten hast dann immer herdamit. ^^

**Comment by bachig26** [comment]
> Ich sehe gerade erst das du aus Deutschland kommst, falls du deutsche streaming seiten hast dann immer herdamit. ^^

Yes, but I haven't spoken German for some time.

If you like, you can see this site which has a collective of all kinds that I use.
https://startseite.to/

**Comment by bachig26** [comment]
@R3tr0Ananas the providers `watchasian` and `viewasian`, both of them are **fetching wrong episodes** and also the **total number of episodes for this show as of today is 637 but it's showing 639, which is also wrong**.
please have a look into this issue, this issue is seen in the both providers.

I have attached the terminal output for both providers below:

#### **From `watchasian`:**
````
The name of the provider [theflix]: watchasian
None
[!] Please Enter the name of the Movie: running man
https://watchasian.la/search?type=movies&keyword=running+man
[1] Kakekomi (2015) TV

[2] Running Man 2015 TV

[3] Running Man (2010) TV

[4] Keep Running: Season 5 TV

[5] Keep Running: Season 1 TV

[6] Keep Running: Season 2 TV

[7] Keep Running: Season 3 TV

[8] Keep Running: Season 4  TV

[9] Keep Running: Season 6  TV

[10] Outrun by Running Man (2021) TV

[11] Keep Running: Season 7 (2019) TV

[12] Keep Running: Season 9 (2021) TV

[13] Running Man International Movie TV

[14] The Running Mates: Human Rights TV

[15] Running Man Korea vs Running Man China TV

[16] Running Man China Vs Running Man Korea 2016 TV

[q] Exit!

[s] Search Again!

[d] Download!

[p] Switch Provider!

[sd] Download Whole Show!

Enter your choice: 3
https://watchasian.la/drama-detail/running-man
Please input the episode number(Total: 639): 637
https://watchasian.la/running-man-2010-episode-635.html
https://dood.wf/e/f944f1hbi5tg
https://dood.wf/pass_md5/81191690-79-230-1673812611-d4e73fd51f9f77b90201135d6403c332/npicdaieuj1otu8vhq9qyehp
https://eo535lo.dood.video/u5kj654n33flsdgge5vvypsdjpmlroh3mvekkijfgfrrpncgpgra7redhkiq/dcjokgnbda~zUEJeL3mUN?token=npicdaieuj1otu8vhq9qyehp
Enter your choice: 3
https://watchasian.la/drama-detail/running-man
Please input the episode number(Total: 639): 638
https://watchasian.la/running-man-2010-episode-636.html
https://dood.wf/e/33x44c56ay8j
https://dood.wf/pass_md5/82022128-79-230-1673812661-e2e6d6e8977e5a288908a1a7ca2b7ed2/ko7h4ysza2kp4dm89i91byqh
https://cc527fo.dood.video/u5kj7dpa5pflsdgge4isgoymlkwvnucldnark3os5hdpaulbh52yncimsyvq/z9ed4moxq1~zUEJeL3mUN?token=ko7h4ysza2kp4dm89i91byqh
````

#### **From `viewasian`:**
````
The name of the provider [theflix]: viewasian
None
[!] Please Enter the name of the Movie: running man
https://viewasian.co/movie/search/running-man
[1] Running Man 2015 TV

[2] Running Man (2010) TV

[3] Running Man (2010) TV

[4] Outrun by Running Man (2021) TV

[5] Running Man International Movie TV

[6] The Running Mates: Human Rights TV

[7] Running Man Korea vs Running Man China TV

[8] Running Man China Vs Running Man Korea 2016 TV

[q] Exit!

[s] Search Again!

[d] Download!

[p] Switch Provider!

[sd] Download Whole Show!

Enter your choice: 2
https://viewasian.co/drama/running-man
https://viewasian.co/watch/running-man/watching.html
Please input the episode number(Total: 639): 638
https://viewasian.co/watch/running-man/watching.html?ep=638
[!] An error has occurred |  'NoneType' object is not subscriptable
````

**Comment by ghost** [comment]
This is happening because viewasian and watchasian are setting some episodes with a .5 at the end which breaks it so. You should use viewasian for this because i take the raw input of the episode number so if you use 564.5 it will use that.

![grafik](https://user-images.githubusercontent.com/83706294/212566636-51266546-eeb9-40d7-93ff-0552a99d86f1.png)

**Comment by bachig26** [comment]
> This is happening because viewasian and watchasian are setting some episodes with a .5 at the end which breaks it so. You should use viewasian for this because i take the raw input of the episode number so if you use 564.5 it will use that.

ah okay, thank you. i didn't know that. 👍
