### ISSUE TITLE
[FEATURE] session

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#95]
**Describe the feature/change you'd like**
When the TUI feature that you're planning comes to public release, please consider including the session feature to remember current provider and current content like ask for next episode instead of exiting to current choice method similar to the reference terminal program that I have attached below.

if possible, please consider in adding the session save option, to replay the content at same time where the user left off, also possible removal of the session memory which this referred program doesn't have.

also the session remembers the option defined to mpv, as can see in the program below while using it to watch an tv series when go to next episode, it remembers the settings of the mpv that was defined in the previous episode as long as if you stay in the same session like for example the stay on top, subtitle size, position that I use.

**Additional context**
please try this program, as I like the TUI is provided here.
reference: https://github.com/Thanatoslayer6/clistream

**Comment by ananasmoe** [comment]
I really don't see the point of adding this.

@THEGOLDENPRO do you?

**Comment by THEGOLDENPRO** [comment]
> I really don't see the point of adding this.
> 
> @THEGOLDENPRO do you?

The first few things mentioned are already being worked on in other issues but the rest would be difficult to implement. *Maybe when the codebase for v4 has matured.* For now I'm going to close this as unplanned.
