### ISSUE TITLE
Scraping Tutorial

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#97]
**Before asking**
Check through [Issues](https://github.com/mov-cli/mov-cli/issues) and closed ones too if your question was already answered.

**Question**
I'm interested in learning and scraping the providers, so I can help in both personally and for the app.
Please let me know on how the scraping works in Python and as it looks easy to understand than other languages that I have previously attached on providers.

If possible, please provider me an guide or tutorial on scraping a site with the existing provider.
eg. what tools to use, how to identify certain things, etc.

**Comment by ghost** [comment]
Tools that i use are:
VSCode, HTTP Toolkit

Things you should learn how to use:
https://beautiful-soup-4.readthedocs.io/en/latest/
https://www.python-httpx.org/
https://docs.python.org/3/tutorial/index.html

Well i am pretty bad at explaining Things, i just looked how @Poseidon444 Scraped Sites and copyed things that i need: Search, Results and so on.

I looked how the Sites get the Links from the providers some like gogoanime have it in the data-video element some get it with ajax. 

Just keep trying trying and trying.

(May contain broken English)

**Comment by Poseidon444** [comment]
I'd recommend techwithtim videos to learn scraping, I'd also suggest you learn some html structuring so that you know what to scrape.
